### ISSUE TITLE
DSpellCheck 1.3.0 64bit is broken with Notepad++ 7.5.1 64-bit

### ISSUE THREAD

**Issue by the-j0k3r** [Predelnik/DSpellCheck#103]
Like title says.

https://github.com/Predelnik/DSpellCheck/releases/tag/v1.3.0
https://github.com/Predelnik/DSpellCheck/releases/download/v1.3.0/DSpellCheck_x64.zip

![capture](https://user-images.githubusercontent.com/31389848/31057655-65fde958-a6de-11e7-915f-7ec45d111f53.PNG)

Tried manually downloading the file, the 32-bit wont even load on Notepad++ 64-bit anyway so had to go back to https://github.com/Predelnik/DSpellCheck/releases/tag/1.2.14.2 adn https://github.com/Predelnik/DSpellCheck/releases/download/1.2.14.2/DSpellCheck-x64.zip which works fine.

```
Notepad++ v7.5.1   (64-bit)
Build time : Aug 29 2017 - 02:38:44
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll PluginManager.dll 
```
DSpellCheck.dll: 1.2.14.2 64-bit works
DSpellCheck.dll: 1.3.0 64-bit broken

**Comment by Predelnik** [comment]
https://drive.google.com/file/d/0B_fsSThBdq2mTk90Y1FGZTFTQ1E/view?usp=sharing
https://drive.google.com/file/d/0B_fsSThBdq2mOE5oN3poczRhX3c/view?usp=sharing
Sorry can you check those two dlls? I made a dumb mistake in believing that cmake somehow started to generate /MT option by default. If they work I will push updated version to plugin manager today.

**Comment by the-j0k3r** [comment]
Could you please make those direct download links? I dont use Google or Microsoft or Mega or whathave you not.

**Comment by Predelnik** [comment]
@the-j0k3r 
Updated links. And looks like they weren't propery public, now it's fixed.

**Comment by the-j0k3r** [comment]
Thank you for that, I couldn't test the 32-bit only 64-bit dll.

Good news though, it worked ;)

![capture](https://user-images.githubusercontent.com/31389848/31070320-c6ff770c-a757-11e7-99f2-858bcdbf9736.PNG)

**Comment by Predelnik** [comment]
Thank you very much for testing! Sadly updating version on plugin manager takes a while but I will push update there soon.

**Comment by the-j0k3r** [comment]
Thats fine with me, thank you for responding and fixing so quickly, surely its appreciated ;)
