### ISSUE TITLE
"ignore ... for Current Session" does not work with DSpellCheck 1.3.0.0 with Notepad++ 32-bit v7.5.1

### ISSUE THREAD

**Issue by Ben-Voris** [Predelnik/DSpellCheck#104]
DSpellCheck 1.3.0.0, using Hunspell, language English (United States), with Notepad++ 32-bit v7.5.1.

Open a new file, type "notindictionary" (assuming you haven't added that to your user dictionary), right-click on it, and click on 'Ignore "notindictionary" for Current Session'. The word is still underlined as are other occurrences of the word.

This defeats my workaround for the CamelCase issue(s).

**Comment by Predelnik** [comment]
Will be fixed in 1.3.2

**Comment by Predelnik** [comment]
Version 1.3.2 is on plugin manager, so ignoring words should work fine now. Feel free to reopen if there's still a problem.
