### ISSUE TITLE
Delimiters are not restored between sessions

### ISSUE THREAD

**Issue by peteter** [Predelnik/DSpellCheck#108]
I specify my Delimters list to: I,.!?":;{}()[]\/=+-^$*<>|#$@%&~…?—«»–•©›“”· `?×¦+-¦+-├─
and click Apply.
Next time I start Notepad++ the list is reset to default.

**Comment by Predelnik** [comment]
It seems to work fine for me. Can you give me some details which version are you using? Is it 64 or 32-bit? Are other options saving on exit? Do you perchance use several instances of Notepad++ simultaneously?

**Comment by peteter** [comment]
Of course...
Notepad++ v7.5.1 32bit
DSpellCheck 1.3.1.0
One session at a time.
Yes, file name extensions are saved/restored OK.

**Comment by Predelnik** [comment]
Hmm so I've tried some different setups and it seems to work, if you don't mind can you send me the config file in case there's problem with it.
It should be in %appdata%/Notepad++/plugins/config/DSpellCheck.ini normally

**Comment by peteter** [comment]
Looking in DSpellCheck.ini;
Delimiters="¦+-¦,.!?":;{}()[]\/=+-^$*<>|#$@%&~…?—«»–•©›“”· `?×¦+-¦+-+-+-¦+-¦"

From what I can tell, my additions (first four, and last 10 something) are there in the file but have been translated to lower ASCII or similar.
I see the same effect now, in what I copy-pasted from the settings dialog in my firt comment :-P Notice the last characters, which, when added in the settings dialog, are "├─", but in the file turns to something like "|+-"

**Comment by Predelnik** [comment]
Thanks! Now I get that.
So this may be the problem of writing unicode to ini file.
Looks like it could be resolved fairly simply:
https://www.codeproject.com/Articles/9071/Using-Unicode-in-INI-files
I will test it soon and inform about the results.

**Comment by Predelnik** [comment]
It seems to fix that fine. So it will be fixed in version 1.3.3

**Comment by peteter** [comment]
I don't have the same problem in 1.3.3. Thanks!
