### ISSUE TITLE
Is 1.3.2 release stable enough?

### ISSUE THREAD

**Issue by donho** [Predelnik/DSpellCheck#112]
Sorry for opening an issue for that, if 1.3.2 release is stable enough?
https://github.com/Predelnik/DSpellCheck/releases/tag/v1.3.2

**Comment by Predelnik** [comment]
Yes I think it is. I plan to release 1.3.3 at the end of the week but it's mostly minor things.

**Comment by donho** [comment]
Just get "Access violation" by closing Notepad++ while DSpellCheck 1.3.2 has been loaded.
Any issue similar from users?

**Comment by donho** [comment]
Another crash due to the opening of "new Document", here is the call stack of main thread:
![image](https://user-images.githubusercontent.com/90293/33244919-503d0f42-d300-11e7-84eb-a9f9fda124d8.png)

**Comment by donho** [comment]
Since Scintilla is not thread safe, and I believe DSpellCheck use the thread to check Scintilla document. I'm wondering what kind of mechanism you use for making sure there's no multiple access to Scintilla?

**Comment by Predelnik** [comment]
> Just get "Access violation" by closing Notepad++ while DSpellCheck 1.3.2 has been loaded.
Any issue similar from users?

Haven't seen anything like this. Is call stack points to DSpellCheck.dll? I actually plan to release 1.3.3 with debug info so it would be easier with crash dumps.

> Since Scintilla is not thread safe, and I believe DSpellCheck use the thread to check Scintilla document. I'm wondering what kind of mechanism you use for making sure there's no multiple access to Scintilla?

Well there shouldn't be more multithread access except for networking anymore and even there it's very local. But technically using SendMessage/PostMessage should not cause any data races as far as I'm aware of.

**Comment by Predelnik** [comment]
Somehow your comment with callstack doesn't appear in this thread, only in my e-mail. The thing is that quite likely DSpellCheck is in call stack because it uses subclassing to hack into context menu but it should pass through all the other messages without changing them, if this isn't the case that definetily should be fixed.

**Comment by donho** [comment]
> Somehow your comment with callstack doesn't appear in this thread, only in my e-mail.

It's nothing to do with DSpellCheck so I delete the post. Sorry for the bothering.

**Comment by donho** [comment]
@Predelnik  FYI: https://notepad-plus-plus.org/community/topic/14846/notepad-7-5-2-release

Software and cathedrals are much the same - first we build them, then we pray.
- Sam Redwine

**Comment by Predelnik** [comment]
Thanks for the heads up :) I hope there will not be any problems this time.

**Comment by donho** [comment]
@Predelnik I realized the DSpellCheck doesn't work in Notepad++ 7.5.2 because the dictionary are bad copied by Installer.
Here's new release of Notepad++ v7.5.3 :
https://notepad-plus-plus.org/community/topic/14873/notepad-7-5-3-release

Let's check again if there is any issue about it.

**Comment by Predelnik** [comment]
@donho 
I tried 7.5.3, and it seems to work fine with English (US) dictionary. Sorry for not checking 7.5.2 properly.

**Comment by chcg** [comment]
@Predelnik 1.3.3 is probably necessary to be bundled with next N++, because of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3968. Is this correct?

**Comment by Predelnik** [comment]
@chcg This isn't 100% clear yet, but seems to be the case. It shouldn't be worse in any way at least.

**Comment by donho** [comment]
@Predelnik 

When my pc get out of hibernation, I tried close Notepad++ then I've got `Access violation` exception (the same situation I have mentionned in the beginning of this thread). This time I got a dump via task manager, and here is the screenshot of dump execution:
![image](https://user-images.githubusercontent.com/90293/33795198-6e7c5094-dcdd-11e7-91aa-1f25afe92b87.png)

Please let me know if you need more information.

**Comment by Predelnik** [comment]
So first of all call stack looks a bit confusing. Especially tiptsf.dll part in it. Maybe it would clarify things a bit if external code would be shown.

I looked that DSpellCheck does on shutdown there's only a couple of interesting things:
- Useless `PeekMessage` loop which I should probably remove but it shouldn't be harmful
- Removal of subclassing through `SetWindowLongPtr`
- `UnhookWindowsHookEx`
Honeslty I don't even know how callstack could get back to Notepad++ after any of these things.

Dump would be more useful with 1.3.3 version of plugin. But I can still look through that to try to determine at least which function in DSpellCheck.dll was called.

**Comment by Predelnik** [comment]
@donho 
I think this issue could be closed since 1.3.2 is already outdated.
Do you still get this access violation when getting out of hibernation by the way?
I would  be happy to look at the dump in either case.

**Comment by donho** [comment]
@Predelnik  Yes, indeed.
Thank you for the investigation and enhancement.
