### ISSUE TITLE
Crash when disabling spell-checking

### ISSUE THREAD

**Issue by vid512** [Predelnik/DSpellCheck#115]
DSpellCheck (version 1.3.2.0) crashes Notepad++ (version 7.5.3 64-bit) every time when I try to disable automatic spell-checking. It happens whether I use menu / ALT-A / toolbar icon. Let me know if you need more info, in case this is not reproducible elsewhere.

**Comment by Predelnik** [comment]
First of all, please try version 1.3.3 https://github.com/Predelnik/DSpellCheck/releases/download/v1.3.3/DSpellCheck_x64.zip
There I fixed one crash which I thought was rare but apparently it's not.

**Comment by vid512** [comment]
Seems fixed in v1.3.3, thanks!
