### ISSUE TITLE
Translations problemms with last versions of plugin

### ISSUE THREAD

**Issue by DmFedorov** [Predelnik/DSpellCheck#116]
in https://github.com/Predelnik/DSpellCheck/issues/114 you have sayed, that "I hope to make beta version in near future."
Please note, that in last version I can not translate some hard coded strings

=======
in version 1.2.14.2 was only one line of such kind:
") as e" (only the right part is extractable for translation)
instead of "Cyrillic: Count io (\\\\ u0451) as e" (duplicate line to dialog 1008)

In v1.3.3 there are completely and partially un-extractable lines (only the right part is extractable for translation).
Text of these lines has not changed, it is visible in UI, but lines can not now be translated

========
completely un-extractable tips to checkboxes in Settings/Advanced:
1) Words like this are mostly mean plural possessive form in English, if you want to add such forms of words to dictionary manually, please uncheck
2) Delay between the end of typing and rechecking the the text after it
3) Remember that words at the beginning of sentences would also be ignored that way.

========
partially un-extractable lines (only the right part is extractable for translation):
1) ictionary directory, otherwise you can change it or run Notepad++ as administrator.
istead of "User dictionary cannot be written, please check if you have access for writing into your dictionary directory, otherwise you can change it or run Notepad++ as administrator."
2) le Languages...
instead of "Set Multiple Languages..."
3) All Users
instead of "For All Users"

**Comment by Predelnik** [comment]
I don't know which tools are you using to extract but these lines seem to be available in plain text inside dll:
![image](https://user-images.githubusercontent.com/2133957/34109199-e40d1d1a-e413-11e7-9831-a80d6cc8ffd3.png)
And I mean mostly it's impossible to have them split without intentional obfuscation. Could it be that it is problem with your tool?

**Comment by DmFedorov** [comment]
I use Radialix. The best tools for translations.
The fact that you and I see the text in Unicode format does not say anything. I can not just replace the text with a translation. These are hard-coded strings. It is necessary to do the link and deduce the text in last line of dll. All this is done by the program for translation, but program does not see some lines or part of them.
If some lines does not see Radialix - then it does not see other tools for translation. I have such an experience.
Something is wrong. And where not so I do not know.
I just reported. You very probably did something not standard. You can try to remember what new was done after the version 1.2.14.2.
At me such first time.
For information (I've talked about this before): the dll analysis lasts 20 times longer than the Notepad ++.exe analysis. But until now everything was fine.

**Comment by Predelnik** [comment]
A lot has changed - I started to compile with latest version of Visual Studio 2017, I attached debug info in 1.3.3. Honestly transferring all strings to resources is more realistic solution than trying to figure out why some custom made utility without source code stopped working. And yes disassembling takes long possibly due to statically linked libraries.

**Comment by DmFedorov** [comment]
v.1.3.2 - Everything is fine, and there I can not see strings yet: 
Enable Debug Logging
Open Debug Log...
After debugging (that nobody will use) 
-----------
I think it started after adding debug info (which increased the size of the DLL twice)

**Comment by Predelnik** [comment]
Ok I can make a special release without debug info for you. I will attach it to releases for 1.3.3 and future versions. Normal version I prefer to be with debug info.

**Comment by DmFedorov** [comment]
I will check the releases once a day.

**Comment by DmFedorov** [comment]
I once again analyzed the "invisibility of hard coded lines" for translation in different versions.
Now I can say: Such lines began to appear since version 1.3.0.
But these lines are not always the same, and those that appeared in 1.3.3 did not coincide with those that were in 1.3.2, so I did not see them and wrote: In v.1.3.2 - Everything is fine.

Summary: Debug Log and the increase in size is not the cause.
I also checked the version before 1.2.14.2. (1.2.14.1 and 1.2.14.0) - there were no invisible lines.

**Comment by Predelnik** [comment]
It's most likely due to change in the compiler but there is clearly no going back in that direction. Code now doesn't compile with compilers older than Visual Studio 2017.
Honestly converting all the strings to STRINGTABLE in resources seems to be much more sane and easier approach.

Here you can try 32-bit version 1.3.3 with no debug info and see if it changes anything:
https://drive.google.com/uc?export=download&id=1HlEj7TwtkA2KP5mbmApWGH9HlLmzMACW

**Comment by DmFedorov** [comment]
======= Honestly converting all the strings to STRINGTABLE in resources seems to be much more sane and easier approach.

O yes. It's only 60-80 lines. I'll send them.
In case the lines are in the dll's STRINGTABLE section, your plugin can be translated even using well known  Restorator. 
And if dll is translated, each new version can be translated using executable file that will repeat  translation already done for lines in executable file, that match lines in new version. 

I will be able to test plugin and answer you only the day after tomorrow.

**Comment by DmFedorov** [comment]
Comparing version 1.3.3 without debug info with versions 1.3.0, 1.3.1, 1.3.2 (in Npp 7.5.3), 1.3.2 (last version), which also do not have debug info, I can say that nothing has changed.

The change of the compiler led to the fact that the usual "correct recognition" of hard-coded strings was violated. This I saw for the first time, although I translated at least 50 programs, among which were simply giants such as Opus or UltraEdit.

The lines (which the translation program sees truncated) change all the time.

As a result of this (visible by eyes) inconvenience I can not translate now some lines.

But apart from this inconvenience there are also other, more serious problems.
Translating hard-coded strings can always disrupt the normal operation of the program.
Especially dangerous are the lines that have several links within the code.
If the translation of such lines violates the work of the program, I can "split the line" by the links and make the translation only to the link that displays the text that I see in the UI.

Now it is almost impossible. The translation program does not see the entire line and I can only exclude all the lines that have several references.
Otherwise, the program does not work.
--------
If you compare the behavior of version 1.3.3 (without debug info) with version 1.3.3 (with debug info) - it works even if I made a translation of the lines with several links.
But despite the fact that the program starts to work I do not have the confidence that it works correctly everywhere.
-------
Summary: I understand that you can not now switch to the old compiler.
However, if you transfer the required hard-coded DLL strings to the RT_Strings section, the problem will be solved completely.

One programmer did, at my suggestion, transfer 90 hard-coded strings to the RT_Strings section in two hours. But he already had such a section in his file ReNamer.exe. (by the way a very complex program)
In your Dll, there is no such section.

**Comment by Predelnik** [comment]
Yes as I said I'm fine with transferring strings to resources. You may send them to me by email predelnik@gmail.com. Technically it's pretty obvious which ones should be translated from but just to double-check. It will obviously be in version 1.4 which may take some time to gets fully realeased.

**Comment by DmFedorov** [comment]
I sent you answer in e-mail.

**Comment by SinghRajenM** [comment]
@Predelnik 

I have a question here. How spellcheck dll with decide which language to show? I'm asking because, in npp++ language can be changed runtime.

Also
> If you can create the "RT_Strings" section in the DLL

If you're planning to move the strings to resource section of dll, then make sure .rc file is unicode. Otherwise few characters for some language will not supported.

**Comment by Predelnik** [comment]
> I have a question here. How spellcheck dll with decide which language to show? I'm asking because, in npp++ language can be changed runtime.

Well, for now we're not talking about it being official localization, just about improving unofficial. I'm not against official localization and it would be amazing if Notepad++ reported its localization in API and notified on its change. I have not yet checked if there are some workaround ways for detecting it (but it's still less desirable)

> If you're planning to move the strings to resource section of dll, then make sure .rc file is unicode.

Thanks for a reminder!

**Comment by DmFedorov** [comment]
After version 1.4.0-alpha2, the future dll changes are fully specified.
Then will follow a long period of finding bugs. Nobody knows what, where and when will find.
Maybe nothing will be found.
However please understand me correctly: every time I must do new Russian dll.
Your 2017 installer is now working not quite properly with respect to hard-coded strings and all the time there is a chance that something might not work because of this.

If it's not hard for you, try first moving hard-coded strings in new section of dll. 
Then testing of dll will take less time and itself will be more qualitative.
I hope that moving such lines will be performed at once and will remain in the past as nasty side-defect of 2017 installer.

**Comment by Predelnik** [comment]
I've already started some movement in that direction but can't promise how fast it will be. Got a little bit caught up with plugin stability fixes currently 😓

**Comment by DmFedorov** [comment]
For information: Creating a localized dll file without hard-coded strings on my computer lasts ~0.5..1 second instead of 110 seconds.
Plus I get a full guarantee that everything works just like in the original. 
And I don't need to spend minimum an hour to checking a huge number of hard-coded lines to provide such a guarantee.

**Comment by Predelnik** [comment]
I've release new alpha version where all requried strings should be moved to resources:
https://github.com/Predelnik/DSpellCheck/releases/tag/v1.4.0-alpha3
You can check if I missed anything. Haven't looked at dialog dimensions for now.

**Comment by DmFedorov** [comment]
missed strings (without a detailed test of the work): 

Ignore "%s" for Current Session¦---context menu in Npp
Add "%s" to Dictionary¦---context menu in Npp
Simple¦---pluginSettings:name of Tab
Advanced¦---pluginSettings:name of Tab
Version: %u.%u.%u.%u¦---dialog about Plugin_filling
DSpellCheck¦---the name of plugin in Npp menu "Plugns" 

(Here in hard-strings you have two strings "Dspellcheck" and one of them has two links. Only translation of all lines "Dspellcheck" gave me the result - translated item in menu Npp "plugns". Although In principle for this menu-item  should translated only one link of one string. But for me the only way was to translate all lines "Dspellcheck". Otherwise the plugin did not work)

**Comment by DmFedorov** [comment]
v1.4.0-alpha3 (bug):
If I switch to Aspell, I immediately get message: 

Plugin crash
HtmlTag_unicode.dll just crashed in 
notify(SCNotification *notification) :
notification->nmhdr.code == 2013
notification->nmhdr.hwndFrom == 02021FCA
notification->nmhdr.idFrom == 0

Then message Runtime error (~ pure virtual call)
**If I remove plugin HtmlTag, then by switch to Aspell I simple get Npp crash**

What's important: by crash created folder (lugins, not plugins) in which are no files:
..Np++\lugins; <DIR>;
..Np++\lugins\Config; <DIR>;
..Np++\lugins\Config\DSpellCheck.ini; <DIR>;

The next time you start Npp, I become Access violation, until switching to hunspell
----------
in v1.3.5 i don't have Npp crash.

**Comment by DmFedorov** [comment]
> Haven't looked at dialog dimensions for now.
http://rgho.st/download/7zFtwDcZG/5f5b07dde4c2a3834993345318be2b891ca456eb/DSpellCheck_1.4.0a3_ru_en.7z
Here you can see my dimensions, in both cases they are the same, only the text is Russian and English.

**Comment by DmFedorov** [comment]
I did not translate these lines before.
If I had seen them, I probably would have understood in context what to translate.
```
%d / ???   bytes downloaded    ¦(what means %d / ???)
L"%d / %d bytes extracted (%d %%)"    ¦what means L - Library?)
Native_Speller
TT
Native (Windows)
```

**Comment by DmFedorov** [comment]
Report about new function "Reload Hunspell Dictionaries" in UserDic.dic for DSpellCeck v1.4.0-alpha3

Everything is working (сhecked on dictionary UserDic.dic)
Deletion and addition work immediately. No sorting.

Creating a file DSpellCeck_Ru v1.4.0-alpha3 lasts maximum 1 second instead of 2 minutes.
100% guarantee for translated file, that it will be work.

----- ---- ----
Disadvantages:
As I said before, when you switch to Aspell, there is a bug, and  items in the plugin menu that should not be used when working with Aspell
(items of submenu "Additional Actions" in this case are separate)

**Comment by Predelnik** [comment]
I've fixed some of the issues in master and release next alpha in a couple of days.
As for Aspell I'm not sure that I fixed the problem but found several typos I've done concerning Aspell and maybe it will fix that problem too.

> %d / ???   bytes downloaded

That happens during download through HTTP proxy as far as I remember there is no way to know the exact final file size, thus it's ????

> L"%d / %d bytes extracted (%d %%)"

L and quotations are typos, I will remove them.

> Native_Speller

This will be removed

> TT

This one is for underline style which looks like T, probably shouldn't be translated.

> Native (Windows)

That's new spell-checker (beside Hunspell/Aspell) which should be available in Windows 8/8.1/10

**Comment by DmFedorov** [comment]
> This one is for underline style which looks like T, probably shouldn't be translated.

I forgot. Yes, this underline style is like flattened T

постарайтесь не забыть недостающие строки:
Ignore "%s" for Current Session¦---context menu in Npp
Add "%s" to Dictionary¦---context menu in Npp
Simple¦---pluginSettings:name of Tab
Advanced¦---pluginSettings:name of Tab
Version: %u.%u.%u.%u¦---dialog about Plugin_filling
DSpellCheck¦---the name of plugin in Npp menu "Plugns"

**Comment by DmFedorov** [comment]
All works. Wow! Perfect!
I have no problem with translation
Thanks you very match.

---- ----
Flattened ттт
Diagonal „„„
Dash ﹍
Dots …
Plain __
Squiggle Low  ﹏
Squiggle ﹏
