### ISSUE TITLE
Settings Dialog ?

### ISSUE THREAD

**Issue by Reconix** [Predelnik/DSpellCheck#117]
![settings](https://user-images.githubusercontent.com/559757/34319789-3c330e6a-e7e2-11e7-888e-a2872edc4c8a.png)

Screen dump says it all, (1.4)

**Comment by Predelnik** [comment]
It's alpha version so while it's not a bad thing to create issues. It just becomes a bit hard to track them. This one for example I already fixed in master.

**Comment by Reconix** [comment]
Understood, thought it might've been a resolution thing, if it's something you're already aware of then great.
