### ISSUE TITLE
DSpellCheck marks common programming/technology words as misspelled

### ISSUE THREAD

**Issue by Starmann** [Predelnik/DSpellCheck#127]
The words list includes:
enum
http
https
ftp
bool
param
inline
xml
xhtml
html

**Comment by Predelnik** [comment]
It's a "problem" of dictionary. Usually default dictionaries does not include words which are not normal English words by default, you have to add them yourself. I don't know if there exists any specialized dictionaries for Hunspell but probably not.
Anyway it has nothing to do with the plugin, right?

**Comment by Predelnik** [comment]
I've written a bit about why bugs about dictionaries are off-topic:
https://github.com/Predelnik/DSpellCheck/wiki/Bug-Reporting#bugs-related-to-dictionaries
You may try address your issue to:
https://github.com/LibreOffice/dictionaries
However as I mentioned usually such words are not added to dictionaries by default so it will probably be considered not issue too.
