### ISSUE TITLE
Recent Problem With .yml

### ISSUE THREAD

**Issue by Puxxup** [Predelnik/DSpellCheck#129]
Hello, I've a problem with the latest version of n++ and win10.
It always worked fine, but recently the plugin doesn't check all the strings but only a part of them.
I've tried all the different settings.
I attach an example file, it's half italian half english. I use italian hunspell dic.

Thank you for your work.
[yml.zip](https://github.com/Predelnik/DSpellCheck/files/1757701/yml.zip)

**Comment by Predelnik** [comment]
Thank you for reporting!
Sadly I've messed up spell-checking of some languages in this release due to refactoring and it's not really easy to check them all but at least for this case you can except fix soon in version 1.4.2

**Comment by Puxxup** [comment]
Ok, no problem. I'll wait. Thank you so much.

**Comment by Puxxup** [comment]
1.4.2 works like a charm again. Thank you so much.

**Comment by Predelnik** [comment]
1.4.3 is now available on plugin manager. Thus this issue is considered fixed.
