### ISSUE TITLE
Unified User Dictionary

### ISSUE THREAD

**Issue by ballios** [Predelnik/DSpellCheck#130]
Why when "Unified User Dictionary" is on - it's impossible to add some words in Dictionary by clicking right  mouse button?
I do it ("Unified User Dictionary" is on in this time) but after Notepad is restarted the words I added to Dictionary is not in it again...
And what this "Unified User Dictionary" option is meaning at all?

**Comment by Predelnik** [comment]
Thanks! Looks like I made a typo about dictionary encoding conversion so words in certain encodings were not working.

> And what this "Unified User Dictionary" option is meaning at all?

It means single user dictionary for all languages, as against one dictionary per one language (in that case there's obviously no encoding problems)

**Comment by Predelnik** [comment]
Version with fix should be available through plugin manager now so this should hopefully be resolved. Feel free to reopen if the issue is still reproducible.
