### ISSUE TITLE
New directory created, on my local N++ configuration, after closing the **DSpellCheck Settings** window

### ISSUE THREAD

**Issue by guy038** [Predelnik/DSpellCheck#131]
**Context** :

Operating system : **Windows XP SP3**

N++ version used : The last version **`v7.5.5`**

**Local** configuration, with the **doLocalConf.xml** file, on directory **C:\\_755**

Download of **DSpellCheck 1.4.1**, **without** the **Plugin Manager**, but directly from the link :

https://github.com/Predelnik/DSpellCheck/releases/download/v1.4.1/DSpellCheck_x86.zip

Installation of the library **DSpellCheck.dll** **`v1.4.1`**, by simple **copy**, in the sub-directory **C:\\_755\Plugins**, which **overwrites** the default **`v1.3.5`** version of **DSpellCheck**

**Issue** :

- Start Notepad++

- Select the option **Plugins > DSpellCheck > Settings...**

- Click on the **Apply** or **OK** button

=> Immediately, under my **C:\\_755** folder, a **new EMPTY** directory **Config\DSpellCheck.ini** is created.

**Remarks** :

- It is important to point out that **DSpellCheck.ini** represents ,really, an **empty folder**

- This **new** folder is created, **before** closing the current N++ session

- If, while N++ is **still** running, you, manually, delete the **Config\DSpellCheck.ini** sub-folders, under the **C:\\_755** directory, it doesn't interfere with **DSpellCheck** and/or **Notepad++** behaviour, which are, both, **correct**

So, in a sense, it's **not** a real bug but, rather, a **weird** action, **without** any consequence on **further** operations

Hope you'll be able to **easily** fix that strange bug, **Sergey**,

Best Regards,

guy038

**Comment by Predelnik** [comment]
Thank you very much for reporting!
Bug may seem to be not serious but it actually indicated of serious typo which could had bad consequences, so it's really great that you noticed it.
Will be fixed in version 1.4.2

**Comment by guy038** [comment]
Hi, **Sergey**

I've just tested your **`1.4.1`** version, on an **W7 64bits** laptop !

I installed the last N++ **`v7.5.5`**, in the folder **`D:\Utilisateurs\pxvr823.380490AS002\Documents\_755`**

As soon as I used the option **Plugins > DSpellCheck > Settings...** and clicked on the **Apply** or **OK** button, the new **folder** **`pxvr823.380490AS002\Documents\_755\plugins\Config\DSpellCheck.ini`** was created, **under** the **`D:\Utilisateurs\pxvr823.380490AS002\Documents\_755`** folder !!

Just for info !

Have a **good time** coding and... resolving that **issue** :-))

Cheers,

guy038

**Comment by Predelnik** [comment]
It should be fixed in 1.4.2 now (which I released today)
You can test it if you like, downloading from here https://github.com/Predelnik/DSpellCheck/releases/tag/v1.4.2
or wait until it will be update on plugin manager.

**Comment by guy038** [comment]
Hi, **Predelnik**

I've just tested your **`v1.4.2`** version : it works **fine**, **no** additional folder created, anymore !

However, note that I did the test, on my **Win XP** laptop, only !

Many thanks for your **quick** feedback, **Sergey** and your **e-mails**, too :-))

Cheers,

guy038

**Comment by Predelnik** [comment]
Since version with fix is available through plugin manager I'm closing this issue.
