### ISSUE TITLE
No spell checking for user-defined languages

### ISSUE THREAD

**Issue by cmagnush** [Predelnik/DSpellCheck#133]
Hi,

This is similar to issue  #129, but for a user-defined language. With earlier versions (at least 1.3.5) I can get spell checking with a user-defined language, but with 1.4.2 I can't. It would be nice to have that back, perhaps with a setting to force-enable checking for some file extensions?

**Comment by Predelnik** [comment]
Can you clarify what do you need to be spell-checked in UDL? I mean it probably makes no sense to spell-check keywords, comments and delimiters should be spell-checkable. Maybe your issue is similar to #132 then?

**Comment by cmagnush** [comment]
Yes, #132 is more like my scenario. Most of the file is plain text - that I want to be spell-checked - and I use UDL to highlight some "non-text" stuff, like markup and similar (that doesn't need to be spell checked, but it doesn't really matter if it is; after all, if I don't have an UDL they are spell-checked).

**Comment by Predelnik** [comment]
Ok please follow #132 for updates then.
