### ISSUE TITLE
Conflict with NPPMenuSearch

### ISSUE THREAD

**Issue by Big--Mike** [Predelnik/DSpellCheck#135]
Hi,

if DSpellCheck and NPPMenuSearch plugins are used together, NotePad++ doesn't exit, but the process stays active in task manager after closing.
See also https://github.com/peter-frentrup/NppMenuSearch/issues/13

My debug info is:
Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : C:\Program Files (x86)\Office\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : AnalysePlugin.dll autosave2.dll ComparePlugin.dll CustomizeToolbar.dll DSpellCheck.dll HexEditor.dll JSMinNPP.dll LightExplorer.dll LocationNavigate.dll mimeTools.dll NppMenuSearch.dll NppQCP.dll NppSaveAsAdmin.dll NppTextFX.dll NppXmlTreeviewPlugin.dll PluginManager.dll ReloadButton.dll

**Comment by Predelnik** [comment]
I'll look into that.
Looks like NppMenuSearch has broken link in plugin manager by the way. I downloaded it from sourceforge and unwanted behavior was reproduced from my side successfully.

**Comment by Predelnik** [comment]
This problem was really confusing for debugging but I figured out that it has to do with subclassing. Reimplementing subclassing in proper way according to https://blogs.msdn.microsoft.com/oldnewthing/20031111-00/?p=41883
seems to resolve the issue.
So it will be fixed in the next version.

**Comment by Big--Mike** [comment]
Thank you for your efforts, I'm looking forward to the next release.

**Comment by Big--Mike** [comment]
I can confirm, that this issue is fixed in version 1.4.4.0
