### ISSUE TITLE
Limit spell-checking for files having extremely long lines.

### ISSUE THREAD

**Issue by Predelnik** [Predelnik/DSpellCheck#136]
There are basically two cases word-wrapped and non word-wrapped. In non wrapped case it's good to consider horizontal scroll. Sadly it looks like there is currently no way to check if word-wrap is enabled or not.
Details:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4461

**Comment by Predelnik** [comment]
Should be mostly fixed with
https://github.com/Predelnik/DSpellCheck/commit/ec41eb2d8e1447d82a0ffe2e5573f652861973cd
but needs to be carefully tested due to possibly breaking other functionality.

Also there seems to be an issue with find next/prev. error on such files related to forced restyling.

**Comment by Predelnik** [comment]
The other thing I noticed is that even if spell-checking takes negligent amount of time after fixes, `SCI_GETSTYLEAT` is much heavier than usual for such documents. Thus it will probably be good to try to avoid rechecking already spell-checked text as much as possible.

**Comment by Ben-Voris** [comment]
I didn’t read all of the context, but it looks like “extremely long” might be 4096. Whatever you consider, please would you document the limit?

**Comment by Predelnik** [comment]
Well it doesn't matter how long - before the fix lines which are partly vislble were checked entirely. Thus extermely long means long enough to slow things down. As an example file which is 100kb but consists of single line would be pretty slow with spell checker enabled.

**Comment by Predelnik** [comment]
Should be resolved with 1.4.4 which is now available through plugin manager.
