### ISSUE TITLE
Can't list directory files for dictionaries

### ISSUE THREAD

**Issue by FrederiqueLesne** [Predelnik/DSpellCheck#137]
Trying to download dictionaries from ftp://ftp.snt.utwente.nl/pub/software/openoffice/contrib/dictionaries/
using the latest update to Notepad++ and DSpellCheck I first had to allow access with Windows Firewall and then restarted Notepad and tried again - keeps saying can't list directory files. 
Tried using Filezilla - same thing.

**Comment by Predelnik** [comment]
Actually ftp://ftp.snt.utwente.nl/pub/software/openoffice/contrib/dictionaries/ seems to work for me but the second one (ftp://sunsite.informatik.rwth-aachen.de/pub/mirror/OpenOffice/contrib/dictionaries/)
no longer contains dictionary files in that location sadly. I guess I have to remove it and try to support downloading dictionaries from LibreOffice GitHub sooner.

**Comment by Predelnik** [comment]
Files are supposed to be unzipped. `.aff` and `.dic` files should be found in specified directory. Tecnically I could support zipped files if it is required.

**Comment by FrederiqueLesne** [comment]
I did unzip them but Dspellcheck did not use the files when I changed the directory path to the new location or when I copied the files into the default folder.

**Comment by Predelnik** [comment]
Have you restarted Notepad++?
List of dictionaries updated only on program start currently.

**Comment by Predelnik** [comment]
I removed non-working FTP from default list with version 1.4.4 which is available through plugin manager. Feel free to reopen the issue if you are still experienecing any problems.
