### ISSUE TITLE
Messages : Exception : vector <T> too long

### ISSUE THREAD

**Issue by guy038** [Predelnik/DSpellCheck#139]
Hello, **Predelnik**,

Sorry, but I afraid that I've found a (small ) **bug**, with your **last** version **`1.4.4.0`** !

First, here is the **Debug info** information :

~~~
Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : D:\@@\Test\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows XP (32-bit)
Plugins : DSpellCheck_1.4.4.0.dll mimeTools.dll NppConverter.dll NppExport.dll 
~~~

So, in a **new** folder, named **Test**, I extracted all the contents of the **npp.7.5.6.bin.7z** archive. However, as this archive contains the **`1.3.5.0`** version of **DSpellCheck**, I downloaded your last version **`1.4.4.0`** and copied it, confirming **overwriting** of the **old** version !

Now, to **reproduce** the bug :

- Start Notepad++ **`v7.5.6`**, for the **first** time

- **Unset**, if necessary, the **Word wrap** feature ( View > Word wrap )

- In the **new 1** tab, write **any** text, even **misspelled**, in order to be **near** the **limit** of the N++ window

- Do **NOT** add any **line-break** to this unique line ( IMPORTANT )

- Now, using the **`Home`** and **`End`** key, you should go, as usual, alternatively, to the **beginning** and to the **end** of this line

- Then, at the **end** of this line, just **add some** characters in order to obtain a line **greater** than the **width** of the N++ window

- Again, do **not** add any **line-break**

- This time, using the **`Home`** and **`End`** key, some messages **`Exception Vector <T> too long`**, should appear !?

---

- Of course these messages, also, happen if :

    - If you **reduce** the **width** of the N++ window, in order that the line **cannot** be **totally** seen
	
	- If you try to move the **horizontal scrollbar**, with the mouse
	
	- If you move from an **other** tab to this **new 1** tab

    - If you increase the **zoom factor**, in order that the line length **exceeds** the N++ window **width**
	
	- ...
	
- Now, as soon as you **end** this **unique** line, in the **new 1** tab, with a **line-break**, the issue **never** occurs, again :-)

- If the **Word Wrap** feature is **off**, this issue does **not** happen, too !

- On the other hand, I tested the **DSpellCheck** versions **`1.3.5.0`**, **`1.4.0.0`**, **`1.4.1.0`**, **`1.4.2.0`** and **`1.4.3.0`**, **without** any trouble !

---
	
Beware, **Predelnik** that this issue could be, simply, related to my **Win XP** system ! **Luckily**, this issue seems to occur, if **DSpellCheck** is scanning an **unique** line, **without** any **line-break**, which **exceeds** the current N++ window **width** :-))

Refer also to :

https://notepad-plus-plus.org/community/topic/15945/error-message/1

Best Regards,

guy038

**Comment by StarMayhem** [comment]
i also have the same issue continuously for a week,
it happen for me when the line long enough to not fit in screen,
scrolling from right to left cause the exception.

**Comment by einst3** [comment]
i dont get the error but the spellcheck underline does not match up on the words for x86 v1.4.4 w/npp 7.5.6. it worked with version 1.4.3. tried it on installed version of npp and portable version. the squiggly lines line up the first time used but then after the second or third launch it goes all squirrely.

**Comment by Predelnik** [comment]
Thank you for reporting. Here's preview version with a fix:
x64 version - https://drive.google.com/uc?export=download&id=13JjF6LI10zuh80Kh_x01rl5gu1-a0rcP
x86 version - https://drive.google.com/uc?export=download&id=13aUEKZtR5-oysXBdODGymQCFSplIVmKh
It would be great if you check that it fixes the issue for you

@einst3 Does it happen on all files? If not it would be great if you send me the problematic file. Also I think it's better to create separate issue for it.

**Comment by guy038** [comment]
Hi, **Predelnik**,

Sorry, but when **starting** Notepad++, with the **`x32`** version of your **fix**, a window pops up, saying, in **French** :

**`The entry point of the procedure InitializeCriticalSectionEx cannot be found in the dynamic link library KERNEL32.dll`**

And then, the **classical** window asking for **removing** that plugin

---

**Sergey**, many thanks for your reactivity ;-))

Cheers

guy038

**Comment by amcoho** [comment]
This also happens on 32-bit Windows 7:

`Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (32-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll`

DSpellCheck version is 1.4.4

**Comment by Predelnik** [comment]
@guy038 
Looks like I somehow compiled it without windows xp support. I will exchange it to the correct version a bit later.

**Comment by einst3** [comment]
the vector fix did not work for me so i openned a new ticket #140

**Comment by Predelnik** [comment]
I updated x86 version to support windows xp, please check.
Same links:
> x64 version - https://drive.google.com/uc?export=download&id=13JjF6LI10zuh80Kh_x01rl5gu1-a0rcP
x86 version - https://drive.google.com/uc?export=download&id=13aUEKZtR5-oysXBdODGymQCFSplIVmKh

**Comment by guy038** [comment]
Hello, **Predelnik**,

I've just tried your **last** fix, and everything went **fine** !

- The plugin was **correctly** loaded, on my **Win XP** laptop

- Now, the issue does **NOT** occur anymore :-)

- And, of course, my **personal** options, contained in **DSpeelCheck.ini**, are **unchanged**

- Many thanks, **Sergey**, for your **fast** resolution of that ( *tiny* ) issue !

Cheers,

guy038

**Comment by Predelnik** [comment]
Closing due to version 1.4.5 with this fix being available in plugin manager.
