### ISSUE TITLE
spellcheck underline does not match up on the words for x86 v1.4.4 w/npp 7.5.6

### ISSUE THREAD

**Issue by einst3** [Predelnik/DSpellCheck#140]
spellcheck underline does not match up on the words for x86 v1.4.4 w/npp 7.5.6. it worked with version 1.4.3. tried it on installed version of npp and portable version. the squiggly lines line up the first time used but then after the second or third launch it goes all squirrely. seems to happen on all files. 
i tried vector fix version but it didnt work.
issue: 1.4.4 seems shifted left
![dspellcheck-144-issue](https://user-images.githubusercontent.com/7558232/41723092-36401fdc-7538-11e8-8c21-f23e37a388f9.png)
correct: 1.4.3
![dspellcheck-143-correct](https://user-images.githubusercontent.com/7558232/41723102-397051a4-7538-11e8-8b62-3b558352c050.png)

**Comment by Predelnik** [comment]
Looks like the problem happens in ANSI (non-UTF8) encoding

**Comment by Predelnik** [comment]
I've added the fix for this issue to the files by the same links I posted in the previous one. Please check if it fixes the issue for you.
> x64 version - https://drive.google.com/uc?export=download&id=13JjF6LI10zuh80Kh_x01rl5gu1-a0rcP
x86 version - https://drive.google.com/uc?export=download&id=13aUEKZtR5-oysXBdODGymQCFSplIVmKh

**Comment by einst3** [comment]
the fix works and all is stable. great job. thanks. keep up the good work. a great piece of software.

**Comment by Predelnik** [comment]
Closing since fix in 1.4.5 is now available through plugin manager.
