### ISSUE TITLE
Add to Dictionary doesn't save to file until session end

### ISSUE THREAD

**Issue by sarahnorthway** [Predelnik/DSpellCheck#142]
Using default Hunspell dictionary, en_US.usr doesn't get updated immediately when I right-click a misspelled word and Add to Dictionary. Instead it's updated when Notepad++ shuts down.

The problem happens if Notepad++ crashes, or Windows freezes, or my machine runs out of battery power while in sleep mode. In that case the custom words are lost and have to be ignored all over again.

I never close Notepad++ and only reboot during a Windows Update. Various work issues sometimes make my machine unstable, so crash/freeze/die happens more often than a clean reboot.

Would be very helpful if en_US.usr was updated either right away, or at least once an hour!

**Comment by Predelnik** [comment]
Was hopefully fixed in 1.4.6
