### ISSUE TITLE
Aspell installed but not working

### ISSUE THREAD

**Issue by Charkel** [Predelnik/DSpellCheck#144]
Hello guys and gals!

I read Aspell is the best and trying to get it to work. I have installed the laterst version of Aspell and all the dictionaries I need. (SWE and ENG) Srangly ENG was missing but SWE was there lol.

Anyways I have browsed to the aspell DLL but it still says Aspell staus: Failed

WTH am I doing wrong? Does it need to run like some daemon? I tried to find something to keep Aspell running but didnt find in list of commands when running Aspell.exe

Please help with expert tips! Do i need an older Aspell Version for Notepad++?

**Comment by Predelnik** [comment]
I checked with aspell from http://aspell.net/win32/ and it seems to work (x86 version only).
Do you use aspell from the same location?

Just to be sure have you tried pressing apply button in settings? It may not be super-intuitive but it needs to be done.

By the way to offer a personal opinion I think aspell is far from the best, it hasn't been updated much and seems to be weaker than other options currently.

**Comment by Charkel** [comment]
Thank you trying to help.
I hope you understand that I'm trying to use Aspell with Notepad++ sorry if DSPellCheck is used for other things and I confusing you.

Yes i installed the GNU Aspell-0.50.3 (win32) from 2002 but do not wanna work

![aspell](https://user-images.githubusercontent.com/19520156/43359741-07dfc7ae-92a8-11e8-9b0d-1542793922da.png)

**Comment by Predelnik** [comment]
Is there a chance you're running 64-bit Notepad++? If that's the case then this version of aspell would not work since it's 32-bit. There is no official 64-bit aspell version binary for windows as far as I can tell, though technically it could be built from sources.

I can make special message for this case if that's confusing.

**Comment by Charkel** [comment]
Oh! Yes well of course I downloaded the 64-bit version. Who's running a 32-bit PC today. Ok i guess that's the solution then. I will uninstall 64bit and install 32 the day that I really feel the need. :)

**Comment by Predelnik** [comment]
Thank you very much for the response!
I will add better error message for such case in the next plugin version. Sadly x64 bit aspell binary is not easy to find, but if I remember correctly I checked that it worked back in the day.

**Comment by Predelnik** [comment]
More detailed message for such case was added in 1.4.6
