### ISSUE TITLE
Option to delete all misspelled words

### ISSUE THREAD

**Issue by 1024mb** [Predelnik/DSpellCheck#147]
So, the title. Can you add an option to remove all misspelled words that are found?

**Comment by Predelnik** [comment]
I don't think it would be useful for mainstream users but I can add it to additional actions here if it's ok: 
![image](https://user-images.githubusercontent.com/2133957/46912637-55af0900-cf83-11e8-9550-35192b7eb7cf.png)

**Comment by 1024mb** [comment]
Yes, please, thanks!

**Comment by iori3000** [comment]
Great, I needed this option today for the most common words 30k which has so many misspelled words.

**Comment by Predelnik** [comment]
Was added in 1.4.8 available through plugin options to "Additional Actions".
