### ISSUE TITLE
How to add a language

### ISSUE THREAD

**Issue by mtrevisan** [Predelnik/DSpellCheck#148]
Hi, I would like my language, Venetan, to be available for Notepad++ to download and use (I think I have to upload some files here ftp://ftp.snt.utwente.nl/pub/software/openoffice/contrib/dictionaries/, I have .aff file, hyphenation file, and thesaurus file). How could I accomplish this?
Thank you

**Comment by Predelnik** [comment]
This FTP is out of my reach sadly but I try to move more towards LibreOffice dictionary repository here on GitHub https://github.com/LibreOffice/dictionaries I don't know which rules do they have for adding new ones but it's probably possible.

Sadly looks like this GitHub repository is only a mirror so you probably need to send a patch through their Gerrit. (More details https://wiki.documentfoundation.org/Development/Dictionaries).

**Comment by mtrevisan** [comment]
Thank you
