### ISSUE TITLE
Remove hotkeys enabled by default.

### ISSUE THREAD

**Issue by Predelnik** [Predelnik/DSpellCheck#150]
Since current hotkeys conflict with normal hotkeys in some other languages based on:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4083
And most of the hotkeys are not needed for average users but in other cases can be configured through Notepad++ easily.

**Comment by Predelnik** [comment]
Done in 1.4.8

**Comment by Carlos3461** [comment]
For those of us who don't want to mess up configuration files will you try to find a way to include short-cut keys for DSpellCheck in a future version?  Not all of us are programmer types and we don't want to be crashing Notepad++ by modifying configuration files!

**Comment by xylographe** [comment]
Select **Settings > Shortcut Mapper > Plugin commands**.
Type `dspell` in the **Filter** input field.
