### ISSUE TITLE
DSpellCheck & Aspell Can't Learn Words?

### ISSUE THREAD

**Issue by gooly** [Predelnik/DSpellCheck#152]
Hi,
I (Win7,64, N++,32) installed DSpellCheck & Aspell. DSpellCkeck now shows the correct library and "Aspell Status OK" in green right beside it, but when I click on a word that is marked as wrong to save it as an additional correct word I get(sic): The File "C:/Program Files (x68)/Aspell/de.pws" cannot be opened for writing.
I installed Aspell and two libraries Aspell-de-0.50-2-3.exe and Aspell-en-0.50-2-3.exe with their defaults - BUT:
1.) Why does N++ want to change a file in C:/Program Files (x68)/Aspell and not in e.g. /Roaming/Aspell?
2.) The file de.pws (and en.pws) is located in C:/Program Files (x68)/Aspell/dict ?

How do I be able to make DSpell&Aspell learn Words in Windows 7? The [installation guide for Notepad++](https://notepad-plus-plus.org/community/topic/8206/method-to-install-gnu-aspell-win32-dictionaries-and-spell-check-plugin-on-n) that I followed does not work for me :(

**Comment by Predelnik** [comment]
So the story here is that it seems to be aspell default to place personal dictionaries inside its own dir at least for installation on windows which seems to mean that it's advisable to install it in write accessible directory (such an outdated way).

Aspell certainly allows to customize itself option by option and I can technically add option for personal dictionaries directory. It also technically allows to specify it in global `aspell.conf` file which should be placed directly to aspell directory but it seems to work only when using it as an application and not as a dll which is frustrating. Oh and also it should support options in some environment variable which also does not seem to work for dll. And moreso dll does not even provide a function to read this config from file. So to support aspell config files I should parse them myself. Such a great library :)

So all in all I think I will just add an option for cutstomizing personal dictionaries location.

**Comment by gooly** [comment]
Well I don't know much about Windows and even less about Aspell. I just know that in Windows the 'unchanged' program files are within C:\Program Files, C:\Program Files (x86) and/or C:\Windows while the custom specific files are located in (e.g. for Aspell): C:\Users\[user-name]\AppData\Roaming\Aspell.
There the user has no problems with files changed by him.
How the Windows registry can be or has to be used - I don't know.

**Comment by Predelnik** [comment]
Implemented in 1.4.8, which is available through plugin manager.
Note that I separated Aspell options (only 2 are supported for now) to standalone dialog which is shown using "Configure Aspell..." button in settings:
![image](https://user-images.githubusercontent.com/2133957/48805003-34320180-ed27-11e8-9511-fc85d473e4ff.png)
