### ISSUE TITLE
Question: What is source of "en_US.dic"

### ISSUE THREAD

**Issue by SinghRajenM** [Predelnik/DSpellCheck#153]
What is the source of "en_US.dic" for DSpellcheck used in Notepad++?

There is [Defect](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4971) logged for notepad.

> "prepend" and "prepended" are valid English words. I don't want them replaced with "perpend" or "perpended".

To handle it, i think we need to change below 
```
prepender
prepends 
```
as 
```
prepend/SDR
```

Correct me if I am wrong.

**Comment by Predelnik** [comment]
I checked that this problem pertains en_us dictionaries from both sources (ftp links do not work in markdown smh): 
ftp://ftp.snt.utwente.nl/pub/software/openoffice/contrib/dictionaries/
https://github.com/LibreOffice/dictionaries

If I remember correctly here is a link with info on how to send corrections regarding LibreOffice dictionaries:
https://wiki.documentfoundation.org/Development/Dictionaries

It could of course be fixed within version provided with Notepad++ exclusively as a temporary measure. My version of plugin does not provide dictionaries with binaries.

**Comment by SinghRajenM** [comment]
Thank you.
