### ISSUE TITLE
Option to Replace all Instances of a Misspelled Word at Once

### ISSUE THREAD

**Issue by MadokaAyukawa** [Predelnik/DSpellCheck#155]
When I right click on a misspelled word, DSC will give me list of suggestions. Many times the same word is misspelled the same way multiple times in the same document. I would like to be able to replace all instances of the misspelled word with the same suggestion at once, instead of going down the document replacing them individually. Perhaps as an additional cascade? SpellingSuggestion1 > Replace All

**Comment by MadokaAyukawa** [comment]
Thank you so much!

**Comment by Predelnik** [comment]
Added as a submenu `Replace all...` in suggestions menu in 1.4.10. Surprisingly this functionality was not at all easy to implement because some nuances (like various letter cases) had to be addressed, if you find behaviour in some case, surprising or inconsistent feel free to report it.
