### ISSUE TITLE
Behaviour of DSpell-Check v1.4.7.0 on, both, v7.5.8 and v7.5.9 versions of Notepad++

### ISSUE THREAD

**Issue by guy038** [Predelnik/DSpellCheck#157]
Hello, **Predelnik**,

I've just tried your **last** DSpellCheck version **`v1.4.7.0`** with the **`3`** N++ versions :

- N++ **`v7.5.8`**

- Original N++ **`v7.5.9`**

- New binary **`v7.5.9`**  ( Refer to:  https://notepad-plus-plus.org/community/topic/16468/notepad-7-5-9-release/39 )

---

And everything went OK, in **all** cases, on my **Win XP** configuration ;-))

**Previous** issues seem **away** : **No error** message, anymore, when **navigating** through files with a **folding** structure or in **`.txt`** file  with a **long** line, without any **line-break** !

Regarding **shortcuts**, I do think it's a **sensible** decision, to avoid possible **collisions**. As for me, I simply **re**-created the previous **`Alt + A`** shortcut to **enable/disable** DSpellCheck !

And, whaaaou ! Your list of all the **misspelled** words are **already** sorted, independently of case ;-))

Thanks, also, for your new option to **delete**  all the **misspelled** words !

In brief, your plugin is a **MUST** one !!

Cheers,

guy038

**Comment by Predelnik** [comment]
Thank you very much for your kind words!
I understand that there is no obvious way to give positive feedback on GitHub but I guess this "issue" would have to be closed after some time.
Have a nice day.

**Comment by Predelnik** [comment]
Closing since this is a non-issue.
Thanks again for your kind words!
