### ISSUE TITLE
Feature request: keyboard shortcut for "special button" menu

### ISSUE THREAD

**Issue by ferenczy** [Predelnik/DSpellCheck#160]
I would like to use the **"special button" menu for suggestions** instead of the context menu but I didn't find any way to open that menu using the keyboard, what's a show stopper for me.

I have to use the context menu option but in that case, the suggestions are mixed up with other menu items and moreover when I open the context menu using the context menu key on a keyboard, it's opened next to the mouse cursor which may be pretty far from the actual word, even on another monitor.

Those are the reason why I would prefer the "special menu" button. But it has to have a keyboard shortcut. Did I just failed to find it or there's none and in that case would it be possible to add such feature, please? Ideally if it would be possible to configure it, there's even Notepad++'s _Shortcut mapper_ which also allows to configure plugins' shortcuts.

**Comment by Predelnik** [comment]
I could add it but probably would not mix it up with "Special Button" just a shortcut/menu item for menu with suggestions and other two options.

**Comment by ferenczy** [comment]
Oh, you mean to have a shortcut which would open the "Special button" menu or the context menu, depending on what's being configured to list suggestions? Yeah, definitely, it wouldn't make a sense much to bind it to the "Special button" menu.

It would be great if you find time to implement it. I would appreciate it.

**Comment by Predelnik** [comment]
Added action `Show Suggestion Menu at Cursor` in 1.4.10, please map your own shortcut to it through Notepad++ shortcut mapper for convenient usage.
