### ISSUE TITLE
"Special button" not displayed when underlined word is at bottom of the viewport

### ISSUE THREAD

**Issue by ferenczy** [Predelnik/DSpellCheck#162]
When there's an underlined word at the bottom of the viewport (just above the status bar so there's probably not enough room for the button), the "special button" to open the alternative suggestions menu is not displayed.

It's not so issue when you can simply scroll the text a bit but when the text is for example so long that it fits the viewport precisely, you have to add some dummy text to push preceding text up a bit first.

**Comment by Predelnik** [comment]
Should most likely be fixed in 1.4.10. Please check if you still have any problems.
