### ISSUE TITLE
Behavior of DSpell-Check v1.4.10.0 and DSpell-Check v1.4.11.0, with the last N++ v7.6.4, on a Win_XP machine

### ISSUE THREAD

**Issue by guy038** [Predelnik/DSpellCheck#170]
Hello, **Predelnik**,

I hope you are well ! Sorry, if this post seems a bit **late** !

On my **Win XP 32-bits** configuration, i get an **error** message when opening Notepad **v.7.6.4** with, either, **DSpell-Check v1.4.10.0** 32-bits and **DSpell-Check v1.4.11.0** 32-bits !

The **error** message says, after translating, from **French** to **English** :

" The entry point of the **GetLocaleInfoEx** process cannot be found in the dynamic link library **KERNEL32.dll** "

Just note that, when using **DSpell-Check v1.4.9.0** 32-bits, in $(NPP_DIRECTORY)\Plugins\DSpellChek\DSpellChek.dll, it's all **OK**

So, **Sergey**, could you do something about it ? Or is my laptop an definitively **"has-been"** thing ;-))

Best Regards,

guy038

**Comment by Predelnik** [comment]
Sorry it was not intended and most likely is due to typo from my side.
Can you check this version please:
https://ci.appveyor.com/api/buildjobs/3qjkpr0hamigyp9m/artifacts/DSpellCheck.dll

If it fixes that problem for you I will try to release a version with the fix soon.

**Comment by guy038** [comment]
Hi, **Sergey**,

Sorry for my **late** reply, due to... the **week-end** ! And I'm **pleased** to confirm you that your **test** version is quite **OK**, on my **`Windows XP SP3 32 bits`** ;-)) I could even test the two **new** additional actions, added in DSpellCheck **v1.4.10.0** : **`Replace with Topmost suggestion`** and **`Show Suggestion Menu at Cursor`** as well as the new **context** option **`Replace All "....." with`** !

Out of curiosity, I compared the **sizes** of the legal DSpellCheck **v1.4.11.0** release and this **test** version  and the latter seems **twice** as small as the legal version ( **`1335Ko`** vs **`2205Ko`** ) ! I suppose that this **test** version is specially dedicated to **`Win XP`** ?

Anyway, all is **fine** and your plugin is really a **must** ! With each **new** release, it seems to me that **nothing** else seems necessary, and yet, you continue to, significantly, **improve** your spelling checker ;-))

BR

guy038

**Comment by Predelnik** [comment]
@guy038 Thanks for the testing! The size will be similar to the previous versions in official release it is just bigger on automated build system for some reason.

**Comment by Predelnik** [comment]
Should be fixed in the version available through plugin admin so closing the issue.
