### ISSUE TITLE
Spell Check not working

### ISSUE THREAD

**Issue by stephenaustin** [Predelnik/DSpellCheck#171]
The app does not appear to work. Not alternate language suggested. Windows 10. 
![image](https://user-images.githubusercontent.com/33739991/55680111-c68a1900-5947-11e9-9b40-d3ee468ac12a.png)

**Comment by Predelnik** [comment]
You seem to be missing dictionaries for some reason, try to press `Download...` to download some.

**Comment by stephenaustin** [comment]
Thanks. I'm only able to install the following dictionaries. 
![image](https://user-images.githubusercontent.com/33739991/55691067-7dc87380-59cc-11e9-974c-d79440b4dc4a.png)
And if I try to install anything I get this error message. 
![image](https://user-images.githubusercontent.com/33739991/55691076-b5372000-59cc-11e9-9dec-6a93b7c4738b.png)

**Comment by stephenaustin** [comment]
![image](https://user-images.githubusercontent.com/33739991/55691087-da2b9300-59cc-11e9-8271-9f7c8333f855.png)

**Comment by Predelnik** [comment]
Do you have `Install for All Users` checked perhaps? It would try to install dictionaries directly to Notepad++ plugin directory which may not be possible.

It also seems like `Show Only Recognized Ones` check box is broken currently so you better turn it off for now too.

**Comment by stephenaustin** [comment]
Thanks for all your help Sergey. I'll take not of everything and use it in the future when similar situations emerge. 

I've reinstalled it and the installation and function of spellcheck seems to be fine now.

**Comment by Predelnik** [comment]
Since the problem was succesfully resolved I'm closing this issue, please feel free to open a new one if you have similar problems in the future.
