### ISSUE TITLE
"Change Current Language" does not show any language(s) when "Spell Check Document Automatically" is disabled

### ISSUE THREAD

**Issue by VolkerBartheld** [Predelnik/DSpellCheck#172]
Seems like there is an issue with displaying the list of languages and changing the current language when automatic spell check is disabled. See these two screenshots:

![20190408_112328_capture](https://user-images.githubusercontent.com/12848904/55713574-3e604e00-59f1-11e9-8116-633ada98619e.png)
![20190408_112410_capture](https://user-images.githubusercontent.com/12848904/55713585-415b3e80-59f1-11e9-82a6-fff2c7c42ab0.png)

They are both from the same installation of Notepad++ (V.7.6.6 64-Bit) and DSpellCheck (V.1.4.11.0) on my Win7x64 system. Just (de)activated "Spell Check Document Automatically" and restarted NP++.

**Comment by Predelnik** [comment]
Yes, apparently this happened due to the fact that I removed loading of Hunspell speller if spell-checking is turned off, it should not prevent loading the list of dictionaries though, so that is a legitimate issue.

**Comment by Predelnik** [comment]
Should be fixed in version 1.4.12+
