### ISSUE TITLE
Spell Check underline not working properly

### ISSUE THREAD

**Issue by Boscox** [Predelnik/DSpellCheck#178]
Just in the last update the spell check underline is only working on the viewport window lines, when you scroll down, there's no more underline spell checks, need to press again the auto button to show the visible lines, if you scroll up again there's no underline on the already underlined lines.

It only underlines the visible words.

By the way, thank you a lot for this you're awesome it helped me a lot in months!!

Thank you, keep the good work

**Comment by Predelnik** [comment]
It should only underline visible words for performance reasons but scrolling up and down (and left/right) should result in rechecking words that became newly visible automatically. If it doesn't happen can you please share with me a text file and describe a little how to reproduce it?

**Comment by Boscox** [comment]
I just opened notepad++ and then updated it by the update pop up like always, then when reopened immediately started to do that on all files, i don't have a clue to how to reproduce it

I'm using notepad v.7.7 and DSpellCheck 1.4.12.0

![underlineBug](https://user-images.githubusercontent.com/12620761/58424211-3fc80180-8097-11e9-82ea-1cf40567e57f.jpg)

**Comment by Boscox** [comment]
Okay I finally fixed this!!

It seems that checking on the notepad++ program files there were missing some files like "config.xml", "langs.model.xml" and folders like "userDefineLangs" and "themes" compared to the npp7.7.zip i just downloaded, this is maybe because I always have installed this program with old version .exe a lot time ago and updated through it missing some files.. dunno but now, extracting the whole zip in the installation folder its working like a charm again!

And seems not your fault, thanks for this my friend and keep the good work!
