### ISSUE TITLE
1.4.13 on npp 7.6.6

### ISSUE THREAD

**Issue by patrickdrd** [Predelnik/DSpellCheck#180]
can I install 1.4.13 on npp 7.6.6?
I cannot update to 7.7 because of problems with greek characters,
so is 1.4.13 backwards compatible?

**Comment by Predelnik** [comment]
I stated it explicitly enough in changelog. Unfortunately the answer is no.

> Warning: Starting with version 1.4.13 plugin is no longer compatible with N++ versions older than 7.7.

**Comment by Predelnik** [comment]
Unfortunately non-issue due to Notepad++ API nature, closing.
