### ISSUE TITLE
Have "Ignore 'Word' for Current Session" in the "Additional Actions" Submenu

### ISSUE THREAD

**Issue by MadokaAyukawa** [Predelnik/DSpellCheck#182]
I have a hotkey for "Find next misspelling" that I use. When I get to a word that I want to ignore, I would like to be able to assign a hotkey for that function instead of having to use the mouse. This would also work well with a hotkey assigned to "Replace with topmost suggestion".

**Comment by MadokaAyukawa** [comment]
There is a very minor issue with the current implementation. I have set a hot key for the above function (thank you for adding it). However, it does not work on the first try. I will use my hotkey for Find Next Misspelling. Then I will want to use the hotkey for Ignore Current Word, but the word is not ignored. I can then right click on the word and chose Ignore or I can go to the Additional Menu and select Ignore Word, then the hotkey will work. So I have to manually ignore a misspelled word once to get the hotkey to activate.

I am using 7.8 and 1.4.14, x64. It did it with 7.7.1 as well.

**Comment by Predelnik** [comment]
Cannot reproduce unfortunately are you sure you don't have the same hotkeys mapped or something like this? Because it is really strange that it works through menu but doesn't work with hotkey.

Also maybe posting content of your `DSpellCheck.ini` from `%appdata%/Notepad++/plugins/config/DSpellcheck` might help

**Comment by MadokaAyukawa** [comment]
According to Notepad++ I have no conflicts with the hotkey.

My config is:
```
[SpellCheck]
Hunspell_Multiple_Languages=en_GB|en_US
Hunspell_Language=<MULTIPLE>
Native_Speller_Multiple_Languages=en-CA|en-US
Native_Speller_Language=<MULTIPLE>
Ignore_Have_Capital=0
Ignore_All_Capital=0
United_User_Dictionary(Hunspell)=1
Library=2
```

**Comment by MadokaAyukawa** [comment]
The above issue seems to only occur when the Library is set to Native. When I set it to Hunspell, it works right away.

**Comment by MadokaAyukawa** [comment]
Little more follow-up. With the library set to Native, using DSC in any way before trying to use the Ignore hotkey will activate it. For example, if I use DSC to correct a misspelling first, then using the hotkey will work. It seems to not work when using the hotkey for Ignore is the absolute first thing you have DSC do.

**Comment by Predelnik** [comment]
Should be working with 1.4.15, including fix for mentioned issue with native speller.
https://github.com/Predelnik/DSpellCheck/releases/tag/v1.4.15
Also available via plugin admin.
