### ISSUE TITLE
Spell Checker skips text in an XML document that uses CDATA

### ISSUE THREAD

**Issue by eSilverStrike** [Predelnik/DSpellCheck#184]
Text in an XML document gets skipped if contained within a CDATA block like so:

```
<page>
<variable name="var1">
    <data><![CDATA[ Some text with a spelling mistake here. ]]></data>
</variable>
</page>
```
CDATA is defined as blocks of text that are not parsed by the XML parser and is needed when your text has special characters or markup (like HTML).

A work around for this is to change the document type in Notepad++ to the default markup.

**Comment by Predelnik** [comment]
Should be fixed in 1.4.14.
