### ISSUE TITLE
Feature request: Extract spelling errors and suggestions for all open documents or selected folder 

### ISSUE THREAD

**Issue by mobcdi** [Predelnik/DSpellCheck#185]
Could the feature to _copy all misspelled words to clipboard_ be extended to include all open documents or a selected folder and then export all misspelled words found and its suggested corrections to a delimited file instead?

Even better if it ranked the output by the frequency of occurrences so most common mispelling and its suggested was at the top

**Comment by Predelnik** [comment]
Somehow I feel requests like this are better suited for command-line utility because it's really specific and the only thing from Notepad++ it uses is open documents list. What benefits it provides if it's Notepad++ plugin function instead of script e.g. in Python?

**Comment by Predelnik** [comment]
I do still feel strongly that it's out of scope, feel free to reopen and prove that I'm wrong if you think so.

My suggestion would be to utilize python interface of hunspell for it: https://pypi.org/project/hunspell/
In that case you might customize output however you wish and it should not be that hard to write such a script.
