### ISSUE TITLE
Feature Request: Disable the "Saving of Settings Failed" dialog box.

### ISSUE THREAD

**Issue by ImSpecial** [Predelnik/DSpellCheck#190]
Hi, I like to set many of my programs "config" files ( .ini / .cfg / .conf / etc. ) as "Read-only" once I have them set up the way I like them, so that they won't change, and the settings are back to how I like them upon relaunching of the program, but with your plugin I get this dialog box when DSpellCheck.ini is set as Read-only;

https://i.imgur.com/Vjlr0Ef.png

Can there be a way to disable this message some how?

**Comment by Predelnik** [comment]
I can definitely disable displaying this on program launch and show it only on pressing apply in settings dialog, however since settings like `spell-check automatically` check box and current language are saved to settings too, your intention may interfere with them being saved.

**Comment by ImSpecial** [comment]
The way I use DSpellCheck is like a toggle, it's not on by default, but I do hit the [ABC button ](https://i.imgur.com/AdH8WAr.png) occasionally to check for spelling, when I hit that button I get the message which is rather annoying.

Ideally this box should only show when pressing OK/Apply in the settings window, letting the user know settings cannot be saved, but even then I wouldn't miss that error noise, lol.

And thanks for considering this at the very least.

Side Note: I also noticed with the newer releases that DSpellCheck that it writes a new DSpellCheck.ini on every launch of Notepad++, even if no settings were touched, is this intentional or a bug?
