### ISSUE TITLE
Extra Languages in the Language Selection Menu in the Settings

### ISSUE THREAD

**Issue by MadokaAyukawa** [Predelnik/DSpellCheck#191]
This may not be a DSC issue. I have a US installation of Win 10. I have the Library selection to Native. Then in the Languages drop down box, I have 4 English options: US, Canada, Philippines, Liberia. I have no idea where the last 3 came from. I have not installed any other languages. In the Language settings in Win 10 itself, I only have English (US) installed and only US is in the drop down box of the Windows Display Language. I can't find any place to delete the extra languages.

**Comment by Predelnik** [comment]
I just use the following function provided by windows api:
https://docs.microsoft.com/en-us/windows/win32/api/spellcheck/nf-spellcheck-ispellcheckerfactory-get_supportedlanguages
I'm not sure that it's related to the languages installed in the system, for me it returns around 100 of options, I have not installed any of them specifically. I also don't know if there's proper way to find out which languages are available through window gui.

Unfortunately I don't know what I can really do about it.

**Comment by MadokaAyukawa** [comment]
Thank you for the explanation. I thought it may be a Windows issue rather than a DSC issue.

**Comment by Predelnik** [comment]
Seems to be working as intended, however filter/custom sorting for languages for native spell checking might still be needed if there's too many unncessary choices but I think it's better to have separate issue for it anyway.
