### ISSUE TITLE
N++ crash on Aspell configure

### ISSUE THREAD

**Issue by chcg** [Predelnik/DSpellCheck#192]
Crash on:

![grafik](https://user-images.githubusercontent.com/12630740/66942984-8ae4b000-f04a-11e9-8bc0-11739f4aae1f.png)

Opening "Configure Aspell ..." leads to N++ crash, if aspell dll is not available.

used DSpellCheck.dll 1.4.14.

> Notepad++ v7.8   (64-bit)
> Build time : Oct  4 2019 - 00:19:37
> Path : C:\Users\chcg\Source\Repos\npp.7.8.bin.x64\notepad++.exe
> Admin mode : OFF
> Local Conf mode : ON
> OS Name : Windows 10 Home (64-bit) 
> OS Version : 1903
> OS Build : 18362.418
> Plugins : BigFiles.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll PythonScript.dll 
>

**Comment by Predelnik** [comment]
`Configure Aspell...` button should be disable in version 1.4.15 when aspell is not found thus preventing crash
https://github.com/Predelnik/DSpellCheck/releases/tag/v1.4.15
which is also available via plugin admin.
