### ISSUE TITLE
Include smart apostrophe in “Ignore words that start or end with '” feature.

### ISSUE THREAD

**Issue by ThomasLeigh** [Predelnik/DSpellCheck#193]
As far as typography is concerned, there are people who prefer so-called *smart* (or *curly*) quotation marks and apostrophes - instead of their straight counterparts. In case of an apostrophe, however, if one uses a curly apostrophe e.g. at the end of a word, it is treated like a misspelling - **even if the *Ignore words that start or end with '* settings item is checked**. 

The curly apostrophe is handled with the same character as [right single quotation mark](https://www.fileformat.info/info/unicode/char/2019/index.htm):

> The official Unicode name for the curly type of apostrophe is ‘right single quotation mark (...) this is [also] the preferred character to use for apostrophe. <sup>( [source](https://cmosshoptalk.com/2019/03/19/smart-apostrophes-cmos-6-117/) )</sup>

**Could the curly/smart apostrophe be included into the *Ignore words that start or end with '* feature?**

**Comment by Predelnik** [comment]
Consideing that there is an option to treat unicode (smart) apostrophe as normal this is very fair. It was applied only to dictionary check unfortunately, I've made changes so it would affect 'ignore apostrophe' and 'treat apostrophe as delimiter' options also.

**Comment by Predelnik** [comment]
Should be working in DSpellCheck 1.4.15
https://github.com/Predelnik/DSpellCheck/releases/tag/v1.4.15
which is also available via plugin admin.
