### ISSUE TITLE
Access Violation in 1.4.14 when Notepad++ starts

### ISSUE THREAD

**Issue by KosMos-pv** [Predelnik/DSpellCheck#194]
I have some large file that opens every time I start N++. This file uses user-defined language but his also happens if you select any document language (c++, html etc). And I get following message:
---------------------------
Plugin Exception
---------------------------
An exception occurred due to plugin: DSpellCheck.dll
Exception reason: Access violation

I can close that window and continue, plugin also works but this message is annoying.
My file is really large, but if I set to use normal text there is no error when I start N++. 
---------------------------
Summary
---------------------------
Full file path: D:\[removed]
Created: 25.11.2015 18:31:25
Modified: 25.10.2019 16:47:27
Characters (without line endings): 1 727 628
Words: 258 868
Lines: 44 982
Document length: 2 667 230
0 selected characters (0 bytes) in 0 ranges

This happens only on current version of plugin. I used 1.4.11 but also checked 1.4.12 and 1.4.13 on same file and version of N++.

Notepad++ 7.8.1 (x86), DSpellCheck 1.4.14

**Comment by OverlordBR** [comment]
Exact the same behavior here. 

And, if i have N tabs opened on Notepad++, N warnings (one for each tab) is displayed.

Same warning: 

Plugin Exception

An exception occurred due to plugin: DSpellCheck.dll
Exception reason: Access violation

**Comment by xylographe** [comment]
Unable to reproduce. Perhaps, this only happens with a specific combination of plug-ins?
Or, perhaps, version of Windows plays a rôle?

Notepad++ v7.8.1   (32-bit)
Build time : Oct 31 2019 - 12:11:14
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.0
Plugins : BetterMultiSelection.dll ComparePlugin.dll **DSpellCheck.dll** ElasticTabstops.dll HexEditor.dll LuaScript.dll mimeTools.dll MultiClipboard.dll NotepadStarterPlugin.dll NppConverter.dll NppEditorConfig.dll NppExport.dll NppQCP.dll NppSaveAsAdmin.dll NppXmlTreeviewPlugin.dll Pork2Sausage.dll SurroundSelection.dll XMLTools.dll

**Comment by KosMos-pv** [comment]
I tested it on clean portable install, only DSpellCheck and default bundled plugins were installed.
Loaded this big file (originally Ren'py scenario but I renamed it to txt as GitHub doesn't allow rpy files), selected any language and restarted N+. After that I got same error.

Notepad++ v7.8.1   (32-bit)
Build time : Oct 27 2019 - 22:46:07
Path : D:\Desktop\npp.7.8.1.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.0
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

[scenario.txt](https://github.com/Predelnik/DSpellCheck/files/3799823/scenario.txt)

**Comment by Predelnik** [comment]
Was able to reproduce it with portable, can't reproduce with installed version for some reason. Anyway I'll look into it.

**Comment by OverlordBR** [comment]
More info to help the degu: 

Notepad++ v7.8.1   (32-bit)
Build time : Oct 27 2019 - 22:46:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1903
OS Build : 18362.418
Plugins : AnalysePlugin.dll BetterMultiSelection.dll ClipboardHelper.dll combine.dll ComparePlugin.dll CsvQuery.dll DocMonitor.dll DSpellCheck.dll ExtSettings.dll HTMLTag_unicode.dll linefilter2.dll LocationNavigate.dll mimeTools.dll MultiClipboard.dll NppBookmarkManager.dll NppColumnSort.dll NppConverter.dll NppExec.dll NppExport.dll NppFavorites.dll NppFTP.dll NppRegExTractorPlugin.dll NppSnippets.dll NppTextFX.dll NppToolBucket.dll PythonScript.dll selectNLaunch.dll SQLinFormNpp.dll

**Comment by kirsan31** [comment]
Same here. Can add that this happens to me only on npp start. So, if npp not running and I start open big file - error occur. But if npp already running - no errors.

**Comment by webdenis** [comment]
@Predelnik Not sure if this is of any help, but my relative has run into this issue as well. 
There were no errors and plugin was used successfully until we have changed the motherboard & CPU during a PC upgrade - we have not reinstalled Windows.

I know it's unlikely, but could it be a hardware related issue?

I wanted to see if 64-bit program & plugin would fix the problem, but the vocabulary my relative uses only supports 32-bit option.

**Comment by Predelnik** [comment]
No, it is a simple mistake coming from trying to write more events to debug log to resolve issue #186.

I fixed it in master and will release new version in a couple of days hopefully.

**Comment by OverlordBR** [comment]
All ok with the 1.4.15 release! 
No more access violation
Thank you!

**Comment by kirsan31** [comment]
Sorry for offtop, but when it will appear in Plugins Admin? Still no update there...

**Comment by Predelnik** [comment]
Plugin admin version is updated manually as far as I know, see `Notepad++ Plugin List Release XXX` commits here:
https://github.com/notepad-plus-plus/nppPluginList/commits/master
Probably it's not connected to Notepad++ version now at least but I'm not entirely sure, anyway I've done my part so after a while it will appear there.

**Comment by KosMos-pv** [comment]
Confirmed, no errors in 1.4.15 release. Closing this issue.
