### ISSUE TITLE
Scrolling hangs after updating NPP 7.7.1 to 8.1 and DSpellCheck

### ISSUE THREAD

**Issue by Big--Mike** [Predelnik/DSpellCheck#196]
### Description of the Issue
After upgrading Notepad (x86) from 7.7.1 to 8.1 navigating with up/down keys in a lengthy document leads to hanging in the editor window (while the status bar line counter still increases). The scrolling instead isn't "smooth" anymore, but the test position "jumps"

### Steps to Reproduce the Issue

1. Install NPP and DSpellCheck plugin
2. Open a lengthy document
3. Press the down key and hold it

### Expected Behavior
The text flows smooth through the window and the cursor position is in the line, the status bar shows.

### Actual Behavior
The display is hanging and the status bar line counter increases, while the cursor stays in the same line

### Debug Information
Notepad v7.8.1   (32-bit)
Build time : Oct 27 2019 - 22:46:07
Path : C:\Program Files (x86)\Office\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 (64-bit) 
OS Version : 1903
OS Build : 18362.418
Plugins : DSpellCheck.dll 

DSpellCheck version is 1.4.14.0
- This didn't happen in NPP 7.7.1
- This doesn't happen if I remove DSpellCheck

So some change from NPP 7.7.1 to 8.1 is causing the problem :(

I've reported it also at the NPP repository:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7542#issue-520635794

**Comment by Predelnik** [comment]
Can reproduce, most likely caused by scintilla update. Will try to debug soon (hopefully).

**Comment by Predelnik** [comment]
I haven't tested it thoroughly but my hypothesis is that scrolling itself became more cpu intensive in that version for some reason and thus calls to spell-checking during it pushes it slightly over the threshold.

I've tested using the timer for scroll updates similar to timer I use for updates on editing and it looks very promising and additionaly it might help with #195. I would probably still have to do a thorough profiling of all the components involved before releasing it, but it is a possible solution.

**Comment by Big--Mike** [comment]
Hi, thank you. I'm looking forward to a release to test :)

**Comment by Predelnik** [comment]
I pre-released 1.4.15 version:
https://github.com/Predelnik/DSpellCheck/releases/tag/v1.4.15
Feel free to test. I would probably double check everything and make a release on a weekend.

**Comment by Big--Mike** [comment]
I would like to confirm this problem is fixed for me with version 1.4.15 :)
Thank you very much!
