### ISSUE TITLE
1.4.15 Causes NP++ Startup delay + Super Minor Thing!

### ISSUE THREAD

**Issue by ImSpecial** [Predelnik/DSpellCheck#197]
Hi, first off thanks so much for fixing #190, works great now!

Okay issue time. I was previously on 1.4.13, and made the jump to 1.4.15 and instantly noticed now that Notepad++ has a slight delay on startup causing a white flash so to speak. This might not be noticeable if you use NP's default theme, but I use Rube Blue, so the white flash is very noticeable, rolling back to v1.4.13 or removing the DSpellCheck plugin all together fixes this issue, but obviously not a very good solution.

A super minor issue I noticed too with the 1.4.15 release yesterday is that now the Underline Style "Squiggle" is very light/faded and hard to read, it's almost like it has opacity at 50% or something, other styles looks fine, I've switched to "TT" for now, and going back to 1.4.13 fixes the "Squiggle" opacity "bug".

Anyways, thanks as always for the continued support of this awesome plugin!

**Comment by Predelnik** [comment]
I've actually removed some leftover stuff I was testing and updated 1.4.15 today so first please redownload it and test it again because I suspect it might be because of it. It's pre-release so things like things like this are unfortunately possible.

**Comment by ImSpecial** [comment]
Just downloaded the new per-release of 1.4.15, and everything seems great, there is no startup delay and the squiggles look the same as ever.
