### ISSUE TITLE
DSpellCheck_x86.zip 1.4.15 (updated) doesn't work

### ISSUE THREAD

**Issue by Big--Mike** [Predelnik/DSpellCheck#198]
Hi,

I've just tried to use your updated plugin 1.4.15 prerelease and Notepad tells me, it's an x64 plugin. Something seems to be mixed up :(

Kind regards

**Comment by Predelnik** [comment]
I have double checked it and it works for me, size also seems to be smaller as it should be. The process of compiling is mostly automated on my side, so it would be very unlikely. Are you sure that everything is correct on your end?

**Comment by Big--Mike** [comment]
Sorry for the inconvenience. 
I've downloaded the archive again and now it's working!

Thank you
