### ISSUE TITLE
Access Violation exception due to DSpellCheck.dll

### ISSUE THREAD

**Issue by DavidHaslam** [Predelnik/DSpellCheck#199]
After I updated **Notepad++** (32-bit) to version **7.8.1** on my **Windows 7 x64** PC, the following error message popup started to appear.

https://www.dropbox.com/s/9j5f97g1er3bavk/Screenshot%202019-11-16%2010.15.44.png?dl=0

- Removing the **DSpellCheck** plugin clears the exception occurrences.
- Re-installing **DSpellCheck** causes it to occur whenever I launch Notepad++.

Aside: This did _not_ occur on another PC that I have access to that runs **Windows 7 x32**.

Further information: I have several other plugins installed. Details available upon request.

**Comment by DavidHaslam** [comment]
Sorry, this may duplicate https://github.com/Predelnik/DSpellCheck/issues/194

**Comment by Predelnik** [comment]
Yes it might be, can you check if it still happens with https://github.com/Predelnik/DSpellCheck/releases/tag/v1.4.15 version first?

**Comment by DavidHaslam** [comment]
Yes - that fixed the issue. _Many thanks_.

It will be nice when this release eventually appears in the Plugins Admin...
