### ISSUE TITLE
Could you add an option to bookmark lines containing misspelled words ?

### ISSUE THREAD

**Issue by guy038** [Predelnik/DSpellCheck#201]
Hello, **Predelnik**,

I'm thinking of an improvement : would it be possible to **add** an option to **bookmark** any line containing, at least, **one misspelled** word ? In some cases, it could be worth to **group/isolate** all these lines for **further** processing !

Do you think it's an **interesting** suggestion ? To my mind, this should **not** need too much coding !

---

BTW, **Sergey**, I noticed that **`DSpellCheck v1.4.15`** is the **last** version supporting **`Windows XP`**. So, even if you consider my **request**, I won't be able to benefit from it unless, of course, I migrate to the **21st** century and buy a **Windows 10** laptop, once and for all ;-))

Best Regards,

guy038

**Comment by Predelnik** [comment]
Hello. It certainly should be possible.

> DSpellCheck v1.4.15 is the last version supporting Windows XP

I mostly decided that because the latest Notepad++ version seems to not suport Windows XP, does it work for you?
For me supporting Windows XP becoming more and more costly also of course since I have to keep Visual Studio 2017 and limit myself to features it supports because it's the last Visual Studio version to support Windows XP.

**Comment by guy038** [comment]
Hi, **Sergey**,

Don't apologize ! I'm the one who's just a bit **stubborn** and who was too **late** to get me a **decent** laptop ;-)

---

I thought of this **improvement** because, at the moment, I'm in the process of putting some **order** and **coherence** in the **directories** and **files**, mainly **photos**, of a friend of my wife. 

As a lot of names are **misspelled**, my idea was to **easily** list all the file/directory names, needing **correction**, with **bookmarks**, adding their **correct** spelling, and then to modify this list into a **command** file, with a **Ren** DOS command at the **beginning** of each line to process !

Thank you, again, for your **prompt** response ;-))

Cheers,

guy038

**Comment by Predelnik** [comment]
Was introduced in version 1.4.16
