### ISSUE TITLE
Notepad++ DSpellCheck not working for latest version

### ISSUE THREAD

**Issue by dddping** [Predelnik/DSpellCheck#203]
## Step
I install the latest Notepad++ (7.8.4  x64) at Win 10. Then manually create a folder under plugins and place DSpellCheck.dll inside.
C:\Program Files\Notepad++\plugins\DSpellCheck\DSpellCheck.dll

## Symptoms
The latest version 1.4.15 is not working, while the 1.2.14.2 working fine (Hunspell dictionary already download in both cases). 1.2.14.2 Is the version that used to work on my old PC.
For 1.4.15, I almost try all setting but still not work. What can I help on this issue? Thanks!

**Comment by Predelnik** [comment]
What exactly is not working? plugin is not loaded or no word is underlined etc.? 
Also it might be a bit of hassle but it would be really nice if you would determine on which version it stopped working because 1.2.14.2 is so very old, even x64 version was beta back then.

**Comment by dddping** [comment]
No error show. But obviously the "Find Next Misspelling" and "Find Previous Misspelling" are not working (also no underline). It just looks like "no misspelling, found".

It stops working at 1.4.0 (1.3.5 work fine). Again, it looks like that 1.3.5 can find misspelling, but 1.4.0 can't, for the same text file.

For switching from/to 1.3.5 & 1.4.0, I just replace the dll file inside Notepad++ plugin folder.

**Comment by Predelnik** [comment]
Does it not work for any dictionary at all, can you check some other dictionaries? (e.g. through `Plugin->DSpellCheck->Settings->Download...`). It might has to do with updating of Hunspell in `1.4.0`. Also please check if native speller works since you are on windows 10 (it can be enabled via `plugins->DSpellCheck->Settings->Library->Native (Windows)`)

**Comment by dddping** [comment]
Hi, the situation is complicate...It work now in my main PC but still not working in other PC. I am tired to try out the symptoms....As long as it work now. Thanks!
