### ISSUE TITLE
Notepad++ crashes

### ISSUE THREAD

**Issue by SinghRajenM** [Predelnik/DSpellCheck#205]
In restricted environment where internet is NOT directly accessible DSpellCheck causes to crash Notepad++.

Pre Conditions:
1. An environment where internet is only available via proxy. Most office work environment is suitable.

Steps:
1. Set proxy in DSpellCheck UI (DSpellChek Settings ->(Library is set to "Hunspell")->Download->Connection Settings...->Use WebProxy).
2. List of available dictionary is available now.
3. Try to Select any dictionary and click on Install Selected.

After step 3, Notepad++ hangs for some time and then crashes (abruptly closes).

**Comment by Predelnik** [comment]
Fix was included in version 1.4.16
