### ISSUE TITLE
Spellcheck not occurring in JSON

### ISSUE THREAD

**Issue by Spappz** [Predelnik/DSpellCheck#207]
Title is fairly self-explanatory; DSpellCheck doesn't appear to highlight any incorrectly-spelt words in JSON strings. Specifically of interest are strings enclosed by double-quotes, such as:
`"string attribute name": "this string attribute contains many words, sume ov wich arre spealt incorectley"`

Appropriate spellchecking does work for JavaScript, which is of course fairly similar in syntax.

**Comment by Predelnik** [comment]
Hello, thank you for reporting the issue. It seems like json lexer appeared a bit later than I've done my last update in that area, I will definetily try to fix that in the next update.

**Comment by Predelnik** [comment]
Should be fixed in 1.4.16. Note that I've put keys to `Function/Variable Names` category (disasbled by default) and values to text (String) category
