### ISSUE TITLE
What was the source of the wordlists distributed with Notepad++ or this plug-in?

### ISSUE THREAD

**Issue by Gitoffthelawn** [Predelnik/DSpellCheck#209]
A few years ago, I think either Notepad++ or this plug-in included wordlists (dictionaries) with the distributions.

From what I can tell, that is no longer the case.

I have a hunspell wordlist in Notepad++ that I think was included with either Notepad++ or this plug-in.  I'm trying to determine the source of this list and how it was created.

My guess is that is that it was created using http://app.aspell.net/create

But when I use that site to create an updated wordlist, I can't generate anything that is close to what I already have.  If I use a SCOWL size of 60, the generated list is much smaller than my current list, and if I use a SCOWL size of 70, the generated list is much larger.

Do you know the source of those wordlists that were distributed with Notepad++ or this plug-in and how they were created?

**Comment by Predelnik** [comment]
Hello, sorry for late reply.

Well I don't know for 100% but they probably were from FTP which is linked in `Download Dictionaries` in plugin (ftp://ftp.snt.utwente.nl/pub/software/openoffice/contrib/dictionaries/)

Basically they should be LibreOffice dictionaries of some old version, currently you can download newer versions from LibreOffice github using plugin.

**Comment by Gitoffthelawn** [comment]
Thank you for your reply.  No problem that it took a little time.

I wonder how OpenOffice created their dictionary.  Any ideas?

From what I can tell, LibreOffice now uses Aspell with a SCOWL size of 60, which is a rather weak dictionary.

I'm looking for, or to generate, a dictionary similar to the one that was distributed with this plugin (or Notepad++), but updated to contain new common words and corrections.

**Comment by Predelnik** [comment]
My current source of up-to-date dictionaries is the following:
https://github.com/LibreOffice/dictionaries

But I have no idea how exactly they are made, neither I know what SCOWL means, I guess you'd better ask contributors to LibreOffice.

**Comment by Gitoffthelawn** [comment]
Thank you for the link!
