### ISSUE TITLE
Spellchecking markdown

### ISSUE THREAD

**Issue by savchenko** [Predelnik/DSpellCheck#211]
This is more of a collective issue for a number of smaller ones:
- Is there an option to skip checking the hyperlinks?
- ...HTML tags
- ...and character escapes, `&mdash;` as an example
- Lastly, not quite sure why completely innocent "in" was highlighted on the screenshot below

![image](https://user-images.githubusercontent.com/300146/80915415-5a1f5a80-8d91-11ea-9914-0dd892ea2528.png)

More than happy to re-shuffle this into the separate issues and do further testing if needs be.

**Comment by Predelnik** [comment]
Sorry but are you using User Defined Language for highlighting markdown or is it somehow included in N++ by default now? 

* For hyperlinks correctly parsed by Notepad++(underlined and clickable etc.) highlighting should not be performed in general but there are few bugged cases unfortunately. However at least some links were not parsed correctly on your screenshot for some reason.
* There's no special parsing done for html tags unless they are highlighted differently like in XML/HTML parsers
* The same as above, html highlighter parses them somehow, so they are excluded
* As for this I don't know, might be something to do with unicode, if you provide me the link to markdown file I can look into that.

So in general UDL parsers are not very good to work with for spell checker unfortunately and writing specific code for excluding certain patterns is something I would really like to avoid. Native support for markdown in scintilla might make things better of course.

**Comment by asvc** [comment]
UDL indeed. I have played with default highlighters and there seems to be something strange going on. 

For example, using Markdown UDL, "bulding" is not highlighted:
![image](https://user-images.githubusercontent.com/300146/80928171-1e60b100-8de2-11ea-860e-e9e9479ce392.png)

"Bitlocker" is highlighted once using "Shell" language:
![image](https://user-images.githubusercontent.com/300146/80928206-8a431980-8de2-11ea-9dee-8e665ed98a45.png)

And twice while using "normal text":
![image](https://user-images.githubusercontent.com/300146/80928217-a5ae2480-8de2-11ea-9169-9f10de33b605.png)

**Comment by Predelnik** [comment]
@asvc Last 2 cases are obvious: in shell the first line was parsed as a comment and the rest was parsed as some form of the code so only the first mention is checked. As for markdown, if [this](https://raw.githubusercontent.com/stoptracking/windows10/develop/README.md) is your file strangely it seems to highlight `bilding` fine for me, and link texts are also not checked, so maybe I'm doing something different or the version of the file is not quite the same.

Also I'm not an expert UDL but most likely specifying that tags and stuff like `&mdash;` are keywords should not be that hard then they will be excluded from spell-checking, this is another approach you can take.

**Comment by asvc** [comment]
[here](https://github.com/stoptracking/windows10/blob/Virt/README.md) is the file in question, however it is very much "live" version &mdash; please expect changes.

> Also I'm not an expert UDL but most likely specifying that tags and stuff like &mdash; are keywords should not be that hard then they will be excluded from spell-checking

That is actually an excellent idea! I might take a look at this closer. Thanks.

**Comment by Predelnik** [comment]
I guess I will mark it as out-of-scope and close since no specific action will be done, spell-checking URLs should be much better starting with 1.4.18 at least, the rest is probably better solved through UDL
