### ISSUE TITLE
DSpellCheck and ligature support

### ISSUE THREAD

**Issue by Big--Mike** [Predelnik/DSpellCheck#214]
Hi, 
I know, this isn't the right place to handle this issue, but I just realized by accident, that you solved an issue, which has been open on the NPP issue tracker since 2016 (https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2287)

It's about ligature support for special fonts, to make look source code "prettier".
The issue over there is about "Fira Code". I'd like to use Microsoft's "Cascadia Code". I've installed the font in my test VM and it looked great. Afterwards I copied it over to my production machine and ligatures didn't work anymore. 

Afterwards I found the issue at GitHub and wondered why it was working on my test VM. I tried my plugins one by one and found, it was DSpellCheck in version 1.4.15, which enabled this feature. It doesn't work with DSpellCheck 1.4.16.

![image](https://user-images.githubusercontent.com/4572946/82693334-a6a7d880-9c61-11ea-93d1-3cfbfa16c599.png)

I'd be pleased if you could implement - whatever you did - again. I guess it had something to do with this: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2287#issuecomment-344063850
I'm going back to the older version of DSpellCheck for now.

**Comment by Predelnik** [comment]
Well it was definitely due to enabling `SC_TECHNOLOGY_DIRECTWRITE` stuff accidentally for testing, I believe I even removed before proper releasing 1.4.15 since it changes behavior of N++ too noticeable (#197)

As for why it's not in N++ at least in the form of an option, I don't know the exact details unfortunately.

**Comment by Big--Mike** [comment]
So, I was lucky, that I didn't update my test installation and had the prerelease of 1.4.15 installed there :-) On my installations I've neither a "white flash" nor problems with the squiggle lines.

For the time, I'll stay with this version, as it works perfectly for me and brings the additional feature of supporting ligatures in fonts.

I hoped to get this feature quickly (back) in DSpellCheck, as I didn't know, it was only special test code in a prerelease. I guess, it's unlikely you'll bring this back (even as an option) under these circumstances.
I don't see the feature implemented in NPP in the near future, as there are several old threads about this issue, over there :'(

Shall we close this issue here?

**Comment by xylographe** [comment]
@Big--Mike 
- Install _LuaScript_ plug-in.
- Select **Plugins > LuaScript > Edit Startup** Script.
- Add the lines below to the _Startup Script_, and save it.
- Restart Notepad++

```
npp.AddEventHandler("OnReady", function()
  editor1.Technology = SC_TECHNOLOGY_DIRECTWRITE
  editor2.Technology = SC_TECHNOLOGY_DIRECTWRITE
  return false
end)
```
Sometimes `SC_TECHNOLOGY_DIRECTWRITERETAIN` might work better (see [documentation here](https://www.scintilla.org/ScintillaDoc.html#SCI_SETTECHNOLOGY)).

**Comment by Big--Mike** [comment]
@xylographe 
Thank you for the hint, I'll have a look at it.
