### ISSUE TITLE
request for documentation

### ISSUE THREAD

**Issue by mtrevisan** [Predelnik/DSpellCheck#215]
Hi, I have a github project on a linter for hunspell, and I wonder if you have any documentation on how hunspell works (that and that of windows), or should I reverse engineer the code?
Thank you

**Comment by Predelnik** [comment]
Hi, unfortunately I'm not a maintainer of Hunspell library but merely a user, so you better address your request at https://github.com/hunspell/hunspell

I do believe they have documentation for library api and file formats for last official version here:
https://github.com/hunspell/hunspell/releases/tag/v1.7.0

**Comment by mtrevisan** [comment]
I understand, thank you.
