### ISSUE TITLE
Access violation when clicking toolbar icon

### ISSUE THREAD

**Issue by Ekopalypse** [Predelnik/DSpellCheck#219]
If I configure a toolbar icon for a pythonscript and press the icon to execute it, I receive an exception window.
Executing the script from within the Plugin menu doesn't generate this issue. Btw. the script is fairly easy, it's printing "Hello Wolrd".

![image](https://user-images.githubusercontent.com/47723516/87431566-1a71bc00-c5e7-11ea-83d6-bd611c2ed540.png)

If there is something else you need me to test or provided, let me now.

**Comment by Predelnik** [comment]
Sorry but how exactly toolbar icon is configured, is it done through some other plugin?

**Comment by Ekopalypse** [comment]
Yes, the PythonScript plugin itself, via its configuration window does this.

![image](https://user-images.githubusercontent.com/47723516/87674631-8afb1300-c776-11ea-936f-515d0cba9a10.png)

**Comment by Predelnik** [comment]
Thank you for report, this issue is completely on DSpellCheck's side as it turns out, will be fixed in the next release!

**Comment by Predelnik** [comment]
Should be fixed in 1.4.17:
https://github.com/Predelnik/DSpellCheck/releases/tag/v1.4.17
