### ISSUE TITLE
Npp Hangs on start with DSpellCheck

### ISSUE THREAD

**Issue by kirsan31** [Predelnik/DSpellCheck#220]
Npp Hangs on start with DSpellCheck (no files loading at start up, i.e only _new_ file. Without this plugin Npp start ok.
DSpellCheck 1.4.16. Win7 pro x64.

[Memory dump file](https://drive.google.com/file/d/1mJS2MUMLp43mQ3ltXYMNxvYQ-jVa_DBB/view?usp=sharing).

And, as I can [see this is not only me / first time issue](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4295#issuecomment-491397352)...

**Comment by Predelnik** [comment]
Thank you very much for report and memory dump, it made it easy to identify the problem. 

<details>
<summary>Technical details</summary>
Uninitialized handle passed to windows api function -> undefined behavior most likely resulting in a hang.
</details>

**Comment by Predelnik** [comment]
Should be fixed in 1.4.17:
https://github.com/Predelnik/DSpellCheck/releases/tag/v1.4.17
