### ISSUE TITLE
DSpellCheck popup: Access Violation

### ISSUE THREAD

**Issue by poxyran** [Predelnik/DSpellCheck#223]
Hello, I'm using Notepad++ with the DSpellCheck plugin but I'm getting a plugin pop up window when I open Notepad++ that says: Access Violation. Here's the debug information from Notepad++:

Notepad++ v7.8.9   (64-bit)
Build time : Jul 15 2020 - 20:31:49
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2004
OS Build : 19041.450
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

The error is showed in admin and non-admin mode.

Attached goes an image with the error. 
<img width="233" alt="dspellcheck_popup_exception" src="https://user-images.githubusercontent.com/2087196/92612642-6e6bea80-f290-11ea-8202-19ac939f51a5.PNG">

**Comment by Predelnik** [comment]
Sorry can you tell which version of the plugin are you using?
If possible please double check with the latest one:
https://github.com/Predelnik/DSpellCheck/releases/tag/v1.4.17

If error persists it would be incredibly useful if you could send me a dump file when error happens via windows task manager:
![image](https://user-images.githubusercontent.com/2133957/92921514-d3fcda00-f43c-11ea-994c-9bfe248a1683.png)
