### ISSUE TITLE
bad allocation

### ISSUE THREAD

**Issue by dontsovcmc** [Predelnik/DSpellCheck#224]
Plugin exception:

An exception occurred due to plugin: DSpellCheck.dll
Exception reason: bad allocation

### Description of the Issue
Open file having incorrect encoding, got error window.

### Steps to Reproduce the Issue
1. Open file with enabled "Spell Check Document Automatically"
Link to file: 
[test.adapter_tibbo_elevator.2020-09-09T21-24-15.log](https://github.com/notepad-plus-plus/notepad-plus-plus/files/5201909/test.adapter_tibbo_elevator.2020-09-09T21-24-15.log)

2. Profit!

### Expected Behavior
Nothing

### Actual Behavior
Error window

### Debug Information
Notepad++ v7.8.7   (32-bit)
Build time : Jun  5 2020 - 02:34:28
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise 2016 LTSB (64-bit) 
OS Version : 1607
OS Build : 14393.3930
Current ANSI codepage : 1251
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by Predelnik** [comment]
Are you sure you are using latest version of the plugin? (because similar bug was fixed a while ago)

If not, can you check with newest version first please:
https://github.com/Predelnik/DSpellCheck/releases/tag/v1.4.17

**Comment by dontsovcmc** [comment]
version was 1.4.6.

1.4.16 works, thanks!
