### ISSUE TITLE
Notepad++ 7.9 crashes when installing a new language

### ISSUE THREAD

**Issue by Legor** [Predelnik/DSpellCheck#243]
I have Notepad++ 7.9 (64 Bit) on Windows 10. 
I've installed DSpellCheck using the Plugin-Manager. It installs version 1.4.17.
The installation works fine, however after trying to add a language, the download bar is visible shortly and NPP shuts down without any further notice. After reopening NPP no language has been installed.

**Comment by Predelnik** [comment]
Please check newer version like
https://github.com/Predelnik/DSpellCheck/releases/tag/v1.4.19
Newer version with small fix for 1.4.19 will also soon be released

**Comment by Legor** [comment]
Hi, it works with the newer version. 
Maybe this should be reflected in the NPP Plugin Manager as well, which installed the older version.

Thanks for the help.

**Comment by Predelnik** [comment]
Unfortunately now it updates when new Notepad++ version is released so it's a bit out-of-sync with plugin updates at certain times, maybe it will improve in the future, though.
