### ISSUE TITLE
Unable to Ignore Some Words

### ISSUE THREAD

**Issue by MadokaAyukawa** [Predelnik/DSpellCheck#251]
In the following file, there are several words that DSC will not ignore, even after selecting that function. Songhwadang and Goguryeo are two examples.

[File.txt](https://github.com/Predelnik/DSpellCheck/files/6136142/File.txt)

**Comment by Predelnik** [comment]
For me it seems to work and I also don't see anything which makes them special (unicode characters or something), very strange

**Comment by MadokaAyukawa** [comment]
I noticed that this is with the Native Win 10 library. I seems to work fine with Hunspell.

**Comment by Predelnik** [comment]
Can confirm that there is a problem on native with multiple languages with regard to ignore/add to dictionary. Ignore for native speller also behaves differently from hunspell in regard that word gets de-ignored if spell-checking is turned/turned off and in some other cases, don't know how serious is this, for now I will fix the problem at hand

**Comment by Predelnik** [comment]
Was fixed since `1.4.21`
