### ISSUE TITLE
How do I turn off Japanese language checking?

### ISSUE THREAD

**Issue by K14Mua** [Predelnik/DSpellCheck#255]
I am translating from Japanese. I need a spell checker for English and Russian. But the plugin considers all Japanese words to be a misspelled word and underlines them. How do I turn off checking for Japanese words?

**Comment by Predelnik** [comment]
This is probably not entirely obvious (seems like I need to rephrase these option names a bit), but try the setting below:
![image](https://user-images.githubusercontent.com/2133957/114863140-09fda480-9df8-11eb-91ca-db3086fd9ff4.png)
It basically makes all non-ascii symbols to be treated as spaces, ignoring words in Japanese successfully.
