### ISSUE TITLE
Note++ Crashes on exit.

### ISSUE THREAD

**Issue by jsarcone** [Predelnik/DSpellCheck#260]
When DSpellCheck is enabled closing NotePad++ crashes. NotePad++7.9.5 and 8.0. DSpellCheck 1.4.20. 
![image](https://user-images.githubusercontent.com/23225346/122066558-db348800-cdc0-11eb-98c6-ef74afb0e18a.png)

This is consistent and reproducible.

**Comment by Predelnik** [comment]
Can you share a dump file via `Task Manager->right click Notepad++->Create dump file`?
You can send it via link on any file sharing service to predelnik@gmail.com or file itself if it fits as an attachment
It would really help me to figure it out. I haven't tested 8.0 yet but 7.9.5 doesn't seem to exhibit such behavior for me.

**Comment by Predelnik** [comment]
By the way could it be that you also using `ExtSetitngs` plugin?
We came to a bit of impasse at fixing this issue unfortunately (see #173)

**Comment by jsarcone** [comment]
I don't have this plugin. Are you suggesting try to use this plugin?
![image](https://user-images.githubusercontent.com/23225346/122101773-b4874900-cde2-11eb-9f55-b3bf45476d22.png)

**Comment by Predelnik** [comment]
No, it's the other way 'round, having it was causing the issue similar to the one you are describing. If you do not have it then it means this issue must be a different one.

**Comment by Predelnik** [comment]
So analyzing your crash dump I observe that it crashes via some actions from `epclient64.dll`.
It seems to be something from Citrix workspace app, I found it causing crashes [here](https://www.reddit.com/r/Citrix/comments/kr1s0z/citrix_epclient64dll_crashes_my_ssh_cygwin/) also but might be unrelated. I will try installing it and see if it is reproducted from my side.

**Comment by jsarcone** [comment]
That is part of App Protection. So, the client must be installed with that. I don’t know if you need the policies enabled.  It is odd this just started happening. I have another system I can test with out the client on it.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by jsarcone** [comment]
I have another system that doesn’t have Citrix Workspaces application no conflict.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

From: Joe ***@***.***>
Sent: Tuesday, June 15, 2021 3:25 PM
To: ***@***.***>; ***@***.***>
Cc: ***@***.***>
Subject: RE: [Predelnik/DSpellCheck] Note++ Crashes on exit. (#260)

That is part of App Protection. So, the client must be installed with that. I don’t know if you need the policies enabled.  It is odd this just started happening. I have another system I can test with out the client on it.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Predelnik** [comment]
It all seems clear now, thank you for posting plugin list even if it was not explicitly requested.
Looks like it is SpeechPlugin unfortunately. 

<details>
<summary>Technical details</summary>

It calls `CoUnitialize` from `DllMain` which Microsoft [recommends not to do](https://docs.microsoft.com/en-us/windows/win32/api/combaseapi/nf-combaseapi-coinitializeex). Basically the thing similar to `ExtSettings`
</details>

But luckily it seems to be maintained by @chcg now, so I'll probably be able to make pull request to fix this.

**Comment by chcg** [comment]
@Predelnik Yes, i did a rebuild of the speech plugin mainly for arm64 support. The plugin uses COINIT_APARTMENTTHREADED as yours, so this should cause no problems. From my understanding of this discussion and https://docs.microsoft.com/en-us/windows/win32/api/combaseapi/nf-combaseapi-coinitializeex:

> Because there is no way to control the order in which in-process servers are loaded or unloaded, do not call CoInitialize, CoInitializeEx, or CoUninitialize from the DllMain function.

these calls should be moved to e.g. 
setInfo()
beNotified()

Is this correct?

**Comment by jsarcone** [comment]
Thank you both for looking into this. I have had both plug-ins for years. I don't know why this just started happening but thank you for looking into this.

**Comment by jsarcone** [comment]
Sorry, I finally had a chance to test this. Works like a champ. Thank you so much for your help please let me know when it gets published. Thank you!

**Comment by Predelnik** [comment]
@jsarcone SpeechPlugin 0.3.1 is available in releases section on github ([link](https://github.com/chcg/SpeechPlugin/releases/tag/v0.3.1)). It would probably be updated on plugins admin with the next N++ release.
