### ISSUE TITLE
Ok, Cancel and Apply can't be pressed on 'simple' tab in settings. Have to navigate to 'Advance' tab.

### ISSUE THREAD

**Issue by PeteMitch99** [Predelnik/DSpellCheck#266]
Ok and Apply button do not work on the 'simple' tab to save settings in 1.4.21. If i click on the 'advance'  tab they work fine.

Win 10. Notepad++ 8.1.1.0

**Comment by Predelnik** [comment]
It seems like it happens only after pressing on some element on a tab but this is obviously a bug, thank you for reporting
