### ISSUE TITLE
Not spell checking Powershell 'comment blocks'

### ISSUE THREAD

**Issue by PeteMitch99** [Predelnik/DSpellCheck#267]
I like this spell checker - well done. I just have one issue with it!

It checks single comments fine. So the below is detected:

#I have been missspelty

However it doesn't check any text in Powershell comment blocks in notepad++, This does not get checked in my ps1 file:

#Start comment block
<#

#I have been missspelty too

I have been missspelty 3

#>

Is there an option I can turn on to check comments blocks - i can't seem to find it?

**Comment by Predelnik** [comment]
Thank you for reporting, will look into that.

**Comment by Predelnik** [comment]
I believe this was fixed starting version `1.4.22`
