### ISSUE TITLE
Spellchecking collapsed code makes UI unresponsive

### ISSUE THREAD

**Issue by L0uisc** [Predelnik/DSpellCheck#273]
I've been working on an [SVD file](https://www.keil.com/pack/doc/CMSIS/SVD/html/svd_Format_pg.html) recently. The `<peripheral>` elements can be 1000s of lines long, so I collapsed all I wasn't interested in. However, this resulted in the Notepad++ UI becoming unresponsive for a few seconds every time I scroll.

Disabling plugins fixed the issue, so I tried to eliminate which plugin causes it. The result is that I found that disabling only DSpellCheck fixes the issue.

I guess DSpellCheck is spell checking all the collapsed lines as well. I think it would improve user experience considerably to ignore collapsed, invisible lines when spell checking. When the user expands them, a spell checking pass can be run over the lines which are now visible on screen. It would cut down on the amount of work done considerably, eliminating the UI lockup.

The file with which I experienced the issue is the following: [STM32F215.svd](https://www.st.com/resource/en/svd/stm32f2_svd.zip)

**Comment by Predelnik** [comment]
Yes this seems like a correct guess and indeed a good idea to fix this, I will try to do it.

**Comment by L0uisc** [comment]
How can I test this fix? Do I have to build the plugin from source?

**Comment by Predelnik** [comment]
If you wish to test the fix before I release the next version, you can download the version built by appveyor  (e.g. https://ci.appveyor.com/project/Predelnik/dspellcheck/builds/41569826/job/r1tox149r8dsvpjg/artifacts). Note that the version built by me will be slightly different e.g. in file size but other than that it should work fine.

**Comment by Predelnik** [comment]
The fix was applied and is available in plugin versions starting 1.4.22
