### ISSUE TITLE
Brazilian Portuguese

### ISSUE THREAD

**Issue by robertboyl** [Predelnik/DSpellCheck#276]
Congrats on DSpellchecker, seems better than the other spell checker plugin for Notepad++.

When I set it to use Windows dictionary, where does it get that from exactly? as my Windows is single language Brazilian portuguese but Dspellchecker is able to check both English and Portuguese. It seems to do a good job. Is there a way to check out the dictionaries it uses when I choose Windows?

The Apell Windows build for Brazilian portuguese is very old, from 2002, comes together with Portugal Portuguse and we had a big language reform in 2009, so that seems too old, I imagined Id have to get a newer compilation somewhere, but this seems to be the main page most people link to, the outdated Windows port of Aspell... http://aspell.net/win32/

I see Hunspell uses Libreoffice, seems the best option for a truly updated PT-BR dictionary, right?

Thanks.

**Comment by Predelnik** [comment]
So it is all resolved by the system in case of Windows spell check, I believe it should come from `Language & region` options and new languages should appear if you install language pack and so on:
![image](https://user-images.githubusercontent.com/2133957/167563369-f8861bba-aa07-43ea-8e5f-1b9f5bbc4a19.png)
For me it seems to be correct at least. Hunspell with LibreOffice dictionaries should work fine as well of course.
