### ISSUE TITLE
Option to Capitalize Word (Perhaps in Additonal Actions)

### ISSUE THREAD

**Issue by MadokaAyukawa** [Predelnik/DSpellCheck#279]
I work on a lot of English subtitles for foreign films/dramas. As such I have a lot of foreign names of people and places that DSC does not recognize. Often times, these proper names are not capitalized for some reason. DSC will recognize them as a misspelled word, but will suggest a wrong word as the names aren't misspelled. 

It would be nice to have an option in the additional actions to Capitalize Word at Cursor, which would also capitalize all instances in the document (just the first letter, not all caps). Or it can be Change Case, going from upper to lower and vice versa, again all instances. It would also be useful in the drop down suggestion box, but that may be harder to implement; additional actions would be good enough as I could bind a hotkey to it. I don't know how hard this would be either way, but hopefully you will consider it. Thank you.

**Comment by Predelnik** [comment]
Maybe I misunderstand the problem but `Replace all with` in context menu should just do it if correct capitalization is in suggestion, for example:
![image](https://user-images.githubusercontent.com/2133957/158033241-cc6a1a58-4a6b-4525-a59d-3c83e082760c.png)
Maybe I don't understand why correct capitalization is not in suggestions in your case, if so could you provide more concrete example.

**Comment by MadokaAyukawa** [comment]
In your example, Dave is a known correct capitalized word. I work with a lot of foreign scripts with foreign names that are recognized as a misspelling in English, but there's no correct capitalized suggestion. In the example below, Madoka is a Japanese name that should be capitalized and Gwangju is a Korean city. They are recognized as misspelled, but no correct spelling is suggested. They are spelled correctly except for the capitulation. This could be an option in the settings to "always suggest a capitalized version of the misspelled word".

![image](https://user-images.githubusercontent.com/44476321/158033645-7af66385-b791-4d30-ab0a-40ed891f05a4.png)

![image](https://user-images.githubusercontent.com/44476321/158033729-c55c5d03-4be0-421a-aed7-5af0b4276aa0.png)

**Comment by Predelnik** [comment]
`Always suggest capitalized spelling` is possible I guess but I'm curious why are you not adding capitalized versions of them in user dictionary though? (in that case they should appear in suggestions)

**Comment by MadokaAyukawa** [comment]
I use an English dictionary so these foreign names are unknown. I don't know if I can get a dictionary of foreign names in English.

**Comment by MadokaAyukawa** [comment]
I made a custom dictionary for Korean cities. And maybe it's supposed to work this way. So DSC now sees the capitalized Gwangju as spelled correctly and the lowercase gwangju as misspelled, but it doesn't suggest the capitalized Gwangju in the drop down menu.

![image](https://user-images.githubusercontent.com/44476321/158038936-a6589be6-43ad-4e3e-a199-17863ffe8397.png)

**Comment by Predelnik** [comment]
Well that should work for Hunspell but might not work with Native spell-checker unfortunately.

**Comment by MadokaAyukawa** [comment]
I see; thank you. I can't seem to get the custom dictionaries to work with Hunspell. I'll stick with Native for now then.
