### ISSUE TITLE
v1.4.22.0 not working on Notepad++ v8.2 (64bit)

### ISSUE THREAD

**Issue by yarow12** [Predelnik/DSpellCheck#282]
It isn't underlining misspelled words or taking me to the next/previous one and I can't download dictionaries.

Having checked a different issue post here (#94), I created the "Hunspell" folder in the "C:\Users\Main\AppData\Roaming\Notepad++\plugins\config" directory, but that solved nothing. Judging by another (#171), I'm probably _missing_ dictionaries altogether.

Uninstalling the plugin and reinstalling (using Plugins Admin) did not work.

![dictionaries](https://user-images.githubusercontent.com/66401444/152079673-9fd35187-0a54-42ff-955e-88f711999cf0.PNG) ![dictionaries fail](https://user-images.githubusercontent.com/66401444/152079681-f08c27a3-0ac1-47f4-bf5d-b2a3006ea300.PNG)

**Comment by Predelnik** [comment]
Can you check if address `https://github.com/LibreOffice/dictionaries` is available to you using a browser? It seems there is some problem with SSL connection but it's hard to download anything without it nowadays unfortunately. Downloading dictionaries manually (.dic and .aff files) and placing to `plugins\config\Hunspell` is also a possible option.

**Comment by yarow12** [comment]
@Predelnik Yeah, I can access the link through my browser fine, but which file(s) should I even download?

**Comment by Predelnik** [comment]
There is `en` folder for english for example and inside there are `.aff` and `.dic` files for various versions/dialects. They could be placed to `%appdata%\Notepad++\plugins\config\Hunspell`

**Comment by yarow12** [comment]
@Predelnik That did it, thanks. For those from the future: [en/en_GB.aff](https://github.com/LibreOffice/dictionaries/commit/96310b850fb350cde8611429292a03ae9167cfa8#diff-7581919f7df93dc6d79a8dbfd8532d7552fd2626d5e9b0ccee789c01a82d571d) and [en/en_GB.dic](https://github.com/LibreOffice/dictionaries/commit/96310b850fb350cde8611429292a03ae9167cfa8#diff-97d95ba52c7e56de24f15e890f1c1068042a807b890d73f19210ce0421b9e0f1).
