### ISSUE TITLE
FR: Option to disable automatic word selection on right-click.

### ISSUE THREAD

**Issue by A1-Gorgon** [Predelnik/DSpellCheck#284]
When using the NP++ context menu for suggestions control, if the cursor is positioned inside (or at the end of) a misspelled word, the entire word is selected when right-clicking. 

While this may be useful for correcting the spelling, it is also problematic when trying to do other things, like pasting text after that word, since it will replace the selected word. Using the keyboard to paste text does work, but the potential for data loss/corruption is still there if I forget, and don't notice it being replaced (even more so when working with columns). There are probably other ways this may interfere with context menu operations as well.

Having the option to disable misspelled word selection on a right-click would be very useful for me. Double-clicking will still select whole words.

Note: The suggestions button does not work properly on this machine, if you are going to suggest using it. The context menu is my only choice.

**Comment by Predelnik** [comment]
I have thought this is a standard behavior but having checked some programs, seems like nowadays no selection is done on right clicking misspelled words basically anywhere, so it might be a good idea to even make this a default behavior I guess.
