### ISSUE TITLE
DSpellCheck plugin underlined words also print with underlines

### ISSUE THREAD

**Issue by Intrepid-MR** [Predelnik/DSpellCheck#285]
Steps to Reproduce the Issue
    1. Click on Plugins, DSpellCheck
    2. Select "Spellcheck document automatically"
    3. Type a misspelled word which will be underline in red
    4. Print the document and the underlining also prints

Expected Behavior
Don't print underlines for "misspelled" words

Actual Behavior
Document prints with words underlined.

**Comment by Predelnik** [comment]
I have tested it with pdf printer and it seems to work correctly with normal `Print...` action. However it seems to no work with `Print Now` and it should be fixed.
