### ISSUE TITLE
Adding dictionaries does not work.

### ISSUE THREAD

**Issue by Wizardling** [Predelnik/DSpellCheck#286]
I try to download them using this plugin's UI, but I only ever get:

![Screenshot 2022-03-12 182836](https://user-images.githubusercontent.com/3980145/158005282-fdf7fdf6-727e-4e93-b06e-5b66e2034ac3.png)

**Comment by Predelnik** [comment]
Most of the time it means that directory `%appdata%\Notepad++\plugins\config\hunspell` is not accessible for writing, at least if `Install for all Users` check box is not on. Can you check if it's accessible?

**Comment by Wizardling** [comment]
I can find no such directory - '\hunspell'

**Comment by Predelnik** [comment]
> I can find no such directory - '\hunspell'

The directory `hunspell` itself would be created automatically but it's important that files could be saved/written to `%appdata%\Notepad++\plugins\config`. You can check by creating any text file in there for example. 

> And yes - I do have Notepad++ installed for all users.

I meant check box in `Download Dictionaries` dialog
![image](https://user-images.githubusercontent.com/2133957/158032897-131fb8f4-436d-44e6-80eb-ef31e622bb9a.png)
It should be turned off preferably.

**Comment by Wizardling** [comment]
Yes, I chose Install for all users when installing the plugin.

I just created a text file in C:\Users\username\AppData\Roaming\Notepad++\plugins\config and had no privilege issues.

**Comment by Predelnik** [comment]
If you have `installed for all users` turned on during dictionary download, Notepad++ should be launched as Administrator most likely. If it is not possible I would suggest turning it off.

**Comment by Wizardling** [comment]
Well, I switched to installing dictionaries for just myself, and that works. I don't want to escalate Notepad++'s privileges unless I absolutely have to.
