### ISSUE TITLE
Post-correction cursor (caret) position.

### ISSUE THREAD

**Issue by ThomasLeigh** [Predelnik/DSpellCheck#288]
I use keyboard shortcut to auto-correct words within which the cursor is placed (or at the beginning or the end of a particular word). Once correction is done the cursor returns to the beginning of the word and most often I need to reposition it. It would improve the workflow if the cursor would be placed at the end of the corrected word.

**Comment by Predelnik** [comment]
Yes this seems like `Replace with Topmost Suggestion` is inconsistent with other types of corrections in this regard. I will fix it.
