### ISSUE TITLE
for help: Cannot work after installed language

### ISSUE THREAD

**Issue by neurojoule** [Predelnik/DSpellCheck#289]
I've tried to find the answer form google but in vain.
The language is already installed as showed
Thank you very much for the kindness of the issue!

<img width="982" alt="image" src="https://user-images.githubusercontent.com/102873492/161394486-64fba4b3-e9f6-4656-9cbd-31f4fbc08302.png">

<img width="239" alt="image" src="https://user-images.githubusercontent.com/102873492/161394534-05edac11-22d1-4a8f-aa10-c6714fc21bb1.png">

<img width="149" alt="image" src="https://user-images.githubusercontent.com/102873492/161394729-2c50e61b-3739-44b1-9599-faaee6201cc9.png">

Notepad++ v8.3.3   (64-bit)
Build time : Mar 13 2022 - 17:20:02
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Users\neuro\OneDrive\桌面-Jam18SP5\私の心わ何もあります.txt"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 2009
OS Build : 22581.200
Current ANSI codepage : 950
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by neurojoule** [comment]
I have it works with "reload" function , thank you!

**Comment by Predelnik** [comment]
Sorry that I did not reply in time, glad that you were able to resolve it.
