### ISSUE TITLE
Weird "Replace All" crash.

### ISSUE THREAD

**Issue by ImSpecial** [Predelnik/DSpellCheck#296]
So I found this happens on "some" .txt files, I say "some" because not all will do it.

As a test, 

- download this "ReadMe.txt" ( https://github.com/UberMedic7/patched-crystal/releases )
- enable the spellcheck
- try replacing something it finds as 'Replace All "...." with'
- should crash

I'm not really sure what to say, using latest notepad++ (8.4.1) with latest DSpellCheck (1.4.23), Win 10 Pro.

https://i.imgur.com/NadRyup.gif

**Comment by ifucan17** [comment]
I'm getting that same problem it has happened to me at least four times. It also causes Notepad ++ to lose some history. When I open it back up the search directory I was working in is lost.

I'm using Notepad ++ 8.4

**Comment by MadokaAyukawa** [comment]
I have the same issue. It happens with one misspelling consistently in one file. I can use Replace All.. on other misspellings without crashing in the same file. I can upload it if you need to test it, but perhaps the file in the OP is enough.

**Comment by Predelnik** [comment]
Unfortunately it's due to scintilla API changes again:
https://sourceforge.net/p/scintilla/bugs/2308/
In this case updated version of the plugin would continue to work with older versions of N++ probably at least.

**Comment by ImSpecial** [comment]
Sorry maybe my coffee hasn't kicked in yet, does that "scintilla API" change mean this feature cannot be fixed? I might have to downgrade notepad++ if that be the case. I rely heavily on "replace all with".

**Comment by Predelnik** [comment]
> Sorry maybe my coffee hasn't kicked in yet, does that "scintilla API" change mean this feature cannot be fixed? I might have to downgrade notepad++ if that be the case. I rely heavily on "replace all with".

It means that it will likely always crash with N++ 8.4+ version without using the updated plugin version which I will try to release soon. If it's important for you when downgrading N++ to earlier version temporary is a possible solution.

The other option is downloading fresh plugin build available from here for example https://ci.appveyor.com/project/Predelnik/dspellcheck/branch/master/job/44m3chxb0u3d69o3/artifacts (64 bit), it might slightly differ from the official build in file size etc. but should generally work.

**Comment by ImSpecial** [comment]
/wipes sweat off forehead

Okay good to know and thanks! I can wait for an official release if one is coming "soon", because not all files do this, strangely enough, so as long as I save first before trying, I should be able to wait.

But good to know of those options too.

**Comment by ImSpecial** [comment]
Okay I couldn't wait lol.

Two things, your appveyor link actually points to the 32-bit version, here's the [**x64 one**](
https://ci.appveyor.com/project/Predelnik/dspellcheck/build/job/cqpfqcxcrd83suca/artifacts) for anyone that cares. :)

The other is, new plugin seems to be working great now!

**Comment by Predelnik** [comment]
Sorry about that I will fix the link in my comment also, just in case.
