### ISSUE TITLE
How to disable the orange color beginning with line ?

### ISSUE THREAD

**Issue by cs-pchsu** [Predelnik/DSpellCheck#310]
Hi all,

DSpellCheck is a nice tool for me to reduce typo in some articles.

However I encounter this issue that there is orange color beginning with line after I installed DSpellCheck.
I show my problem in the attachment strange_orange_color.jpg.
![strange_orange_color](https://user-images.githubusercontent.com/21957111/197464043-e12c146a-b9fb-4dae-8911-93220a77108b.jpg)
Can someone tell me how to disable the orange color beginning with line ?

Thanks,
PC

**Comment by silentbrains** [comment]
If it is the vertical orange line, it is a new feature in Notepad++ that tracks edits and is unrelated to DSpellCheck.
More info (including how to turn it off):
https://community.notepad-plus-plus.org/topic/23616/faq-desk-new-change-history-feature

**Comment by cs-pchsu** [comment]
Hi silentbrains,

Thank you for your help.

Although this is unrelated to DSpellCheck, but you actually solved my problem.

Thanks,
PC
