### ISSUE TITLE
Bookmarking Misspellings Conflict with New Change History Margin

### ISSUE THREAD

**Issue by MadokaAyukawa** [Predelnik/DSpellCheck#313]
With the new Change History Margin, and when trying to bookmark all misspellings, DSC will now place them in the change history margin rather than the Bookmark margin.

![image](https://user-images.githubusercontent.com/44476321/218393518-8be83d0e-559f-4fb5-98a7-57d55e69e8b4.png)

This FAQ talks about the margin and the consequences for plugins:

```
Consequences for Plugins

In order to support the Change History feature, Notepad++ had to reassign some resources it was using for other purposes, because Scintilla used these same resources for Change History. Summary: The marker id number for bookmarks changed from 24 to 20, and three marker id numbers used for the hidden-lines feature changed from 21-23 to 17-19.

Further, Change History uses Margin number 2, so that is no longer available to plugins.

Plugins that made use of affected marker-numbers or margin 2 will have to be updated in order to not conflict with Notepad++'s use. If they are not updated, there will be unexpected interactions, and users will be confused.
```
https://community.notepad-plus-plus.org/topic/23616/faq-desk-new-change-history-feature

Thank you for a wonderful plugin.

**Comment by Predelnik** [comment]
Thanks for reporting, will certainly fix this soon.
