### ISSUE TITLE
Dark mode compatibility

### ISSUE THREAD

**Issue by gmikhail** [Predelnik/DSpellCheck#314]
The current DSpellCheck icon in dark mode looks like this:

![dm](https://user-images.githubusercontent.com/4838367/218542309-355b1e3f-c801-4790-9ff8-95a550d3df03.png)

Please add a compatible icon (just change icon text to white).

---

Dark mode has been added in Notepad++ v8: https://community.notepad-plus-plus.org/topic/21273/notepad-v8-release-candidate-3

New API description: https://community.notepad-plus-plus.org/topic/21652/add-new-api-nppm_addtoolbaricon_fordarkmode-for-dark-mode

**Comment by Predelnik** [comment]
Thanks for reporting, looks like it would not be hard to fix.
