### ISSUE TITLE
On Windows 11 does not appear to work "out of the box"

### ISSUE THREAD

**Issue by aceastwood** [Predelnik/DSpellCheck#320]
On a totally new Windows 11 Machine I installed notepad ++ then DspellCheck. Then tried to download a dictionary.   No matter what I did it always gave the error **"Cannot create directory  .\plugins\config\Hunspell"**

Even after I had manually created this directory it still gives the error.  Fortunately I was able to go to Github find the dictionary file in total, download, unzip  and find the.aff and .dic file I needed.

I'm a retired systems architect and even for me navigating around the windows system to its various querky mislabled " appdata" "roaming" directories is **heavy going.** Most ordinary  folks would simply give up and would not know what to do with Gihub either. 

  Hot tip:   in error message like "Cannot create directory  .\plugins\config\Hunspell" is very easy to ask the file system to expand what  "." represents  as your users will not know anything about where home ('".") is.

**Comment by Predelnik** [comment]
Technically this error message should appear only when `Install for All Users` checkbox is enabled, but I agree that having `.` in directory name makes it unclear that directory is expected to be relative to Notepad++ executable.
