### ISSUE TITLE
Spell checking doesn't work for GDScript 

### ISSUE THREAD

**Issue by VideoGirlAi** [Predelnik/DSpellCheck#323]
I updated to the latest version of Notepad++ which has support for GDScript. As I am making a game in Godot, I use GDScript, and I like using Notepad++ to edit scripts and fix spelling. However now that GDScript is officially supported in Notepad++, spell checking doesn't work anymore. It seems that it does not recognize strings or comments in GDScript.

**Comment by Predelnik** [comment]
Yes updating plugin for GDScript is needed, will do that soon
