### ISSUE TITLE
Assign some keyboard shortcut to the "Find next" menu item

### ISSUE THREAD

**Issue by trejder** [Predelnik/DSpellCheck#324]
Thank you for your time developing this fabulous plugin! I can't imagine my work in Notepad++ without it. And it is always the first plugin that I install to N++.

However, there is a one thing that drives me crazy.

**Can we have any keyboard shortcut assigned to or any way to automate finding next mistake?**

It is totally counter-productive, if not absurd to click _Plugins_ → _DSpellCheck_ → _Find Next Misspelling_ menu item, if you have hundreds of mistakes to find and correct in single file.

**Comment by Predelnik** [comment]
It can be assigned yourself using `Settings->Shortcut mapper->Plugin Commands->Find Next Misspelling`.
Is it inconvenient for you to do so for some reason?
Unfortunately it's not easy to select a unique default shortcut because some popular plugins may also have used some hotkeys for their actions.

**Comment by trejder** [comment]
I did not know that shortcuts configuration is application-wide and I was looking in the plugin configuration itself. I think that adding some simple label, saying that shortcuts should be configured there and there would ease users like me.

Anyway, after checking this it clearly seems that either I am doing something wrong or the whole thing simply isn't working at all.

Shortcuts are defined:

![Clipboard00](https://github.com/Predelnik/DSpellCheck/assets/2903392/6465b717-0397-4f82-a684-12010f6bac5d)

And upon saving the dialog, you can clearly see that Notepad++ has assigned them to the corresponding menu items:

![Clipboard01](https://github.com/Predelnik/DSpellCheck/assets/2903392/a9df5699-e21e-41a7-8efd-5430487a2324)

But, upon pressing any of these two shortcuts → nothing happens. No effect at all. Neither "new" (DSpellCheck-related) comments nor "old" ones (search-related) are triggered. Notepad++ does nothing and acts like no key would be pressed.

Additionally, when closing Notepad++ for the first time after new shortcuts has been defined, I saw this warning message:

![Screenshot 2023-07-23 155131](https://github.com/Predelnik/DSpellCheck/assets/2903392/89a0bd65-befe-45c7-98bd-e4c77e44fcd4)

I completely don't understand it. I already have Notepad++ 8.5.4 (so newer than mentioned 8.5.2). In theory I should not see this message at all, if I am getting things correctly.

**Comment by Predelnik** [comment]
I think when the line with hotkey is highlighted in red it means that Notepad++ thinks there is conflict there and to make anything work you have to go to the other conflicting shortcut and clear it, that's not very convenient but falls out of scope of this plugin development obviously.

As for suggestion on how to set shortcut I can try to add something like this, will think about it.

**Comment by trejder** [comment]
Yes, after clearing the original shortcut, everything now works just fine. Thank you. Closing this ticket.

It is up to you, but I'd add a short notice, where to configure shortcuts for DSpellCheck and what to do in case of conflict.
