### ISSUE TITLE
[FEATURE REQUEST] Disable spell checker while printing

### ISSUE THREAD

**Issue by WalterHof** [Predelnik/DSpellCheck#328]
### Description of the Issue
Spell checker marks unknown words with an red underline. Printing a document with enabled spell checker,
prints these unknown words with an red underline. This is in most cases not useful and not wanted.

### Expected Behavior
Allow printing without the red underline. I. e. automatically disable the spell checker.
Please add an option to disable spell check while printing and re enable spell check after printing.

**Comment by Predelnik** [comment]
It was fixed to work with recent Notepad++ versions in the latest version
https://github.com/Predelnik/DSpellCheck/releases/tag/v1.5.0
Can you please tell which versions of plugin and Notepad++ do you currently have?

**Comment by WalterHof** [comment]
Hi,

 
I used Notepad++ 8.5.6 and DSpellCheck 1.4.24. Today I updated to Notepad++ 8.5.7 and DSpellCheck 1.5, with this updates, the red misspellings marks are gone when printing.

 
Thank you.

 
Mit freundlichen Grüßen

Walter Hofstädtler

 
 
Von: Sergey Semushin ***@***.*** 
Gesendet: Dienstag, 19. September 2023 21:18
An: Predelnik/DSpellCheck
Cc: Walter Hofstädtler; Author
Betreff: Re: [Predelnik/DSpellCheck] [FEATURE REQUEST] Disable spell checker while printing (Issue #328)

 
It was fixed to work with recent Notepad++ versions in the latest version
https://github.com/Predelnik/DSpellCheck/releases/tag/v1.5.0
Can you please tell which versions of plugin and Notepad++ do you currently have?
