### ISSUE TITLE
Underling style automatically change

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [Predelnik/DSpellCheck#36]
Hello, I have some annoying bug. In option I set for underling style:
- red
- squiggle

And its work fine, when make error the words use this style. But if I minimize program and back to full window color red is chagne to blue and squiggle to plain. In Settings its still red and  squiggle but in Npp window its changed. I must restart Npp or click Apply in Settings.

Maybe some plugin break this,  if necessary I add more information.

**Comment by ArkadiuszMichalski** [comment]
Quick Color Picker 2.0 was fixed, this problem not exist in actual version of NPP, DSpellCheck and Quick Color Picker 2.0, so bug can be close.

**Comment by Predelnik** [comment]
Bug can be closed as mentioned above so I'm closing it 😉
