### ISSUE TITLE
Feature request: CamelCase spell check in code

### ISSUE THREAD

**Issue by janschreiber** [Predelnik/DSpellCheck#37]
Common behavior for spell checkers that are intended for coding is to turn off checking for everything except comments and strings.
But in quite a lot of software projects, function and variable names consist of plain ordinary English words, often in camel case, such as OnEventReceive( trigger ). Why can't we have those spell-checked, too, only in a novel way?
The idea: If a word is inside a code area, _just split it up at the word boundaries marked by the case changes_ before sending the chunks to the underlying spell-checker (Hunspell or Aspell). In our example, you would send "on", "event", and "received", so, no problem.
If they return for any of the chunks that it is misspelled, mark the function or variable name as misspelled and generate suggestions based on concatenating the suggestions.
For example, if I mistype "OnEventReceive" as "OnEventRecieve", I would expect the following to happen: Aspell suggests "receive" as replacement for "recieve", while not complaining about the other two chunks. As a result, DSpellCheck suggests "OnEventReceive".
I think that could save quite a bit of hassle, in particular when working with a multi-national team.
Obviously, it must be made optional though, because for some projects it won't make sense at all.

**Comment by RenniePet** [comment]
First off, thank you very much for DSpellCheck - I love it and use it all the time.

Second, this is an old thread, but I would like to cast a vote for implementing this feature, which is relevant for both "camel case" and "Pascal case" identifiers or compound words.

For example, I just noticed that I made a spelling mistake in a document some three years ago - how embarrasing:

  4. Write-to-disk support (FileWritter class)

It should, of course, be FileWriter class. 

I'm sure Notepad++ is used a lot for documenting programs written in C# and Java and lots of other programming languages where "compound words" are used as identifiers. 

Thank you.

**Comment by Ben-Voris** [comment]
I'd really like to be able to tell DSpellCheck that (for example), argleBargle is a valid word with only that capitalization. This is common with technical documentation where the match must be exact. That is, I should be able to make DSpellCheck valid but have DspellCheck, dspellcheck, dspellCheck, etc. flagged as a misspelling. 
This seems related to https://github.com/hunspell/hunspell/issues/468 and https://github.com/Predelnik/DSpellCheck/issues/89

**Comment by Predelnik** [comment]
Yes and like I mentioned in #89 tokenization is completely on side of the plugin so it is not directly related to hunspell issue. It's just a possible improvement on plugin side.

**Comment by Predelnik** [comment]
CamelCase word tokenization is implemented in 1.4.0 which is avaialble through plugin manager.
It it currently disabled by default and have to be enabled using this check box:
![image](https://user-images.githubusercontent.com/2133957/36352031-63d66cce-14c3-11e8-9a8d-d639ca4e8095.png)
I noticed that it breaks spell-checking of Scottish surnames if enabled by default but I'm not sure if it's that important, maybe I will make it turned on by default later on.
