### ISSUE TITLE
Multiple Languages

### ISSUE THREAD

**Issue by RonnyRusten** [Predelnik/DSpellCheck#45]
Hi.
Hope this is the right place to report this, I'm sorry if it's not.

I have selected English (US) and Norwegian, and if I select some text and then rightclicks my selection is removed.
The result is that when I try to copy text, nothing is copied to the clipboard.

If I select only English or only Norwegian it is working fine.

**Comment by Predelnik** [comment]
This issue was fixed but not closed. Shame on past me. Closing.
