### ISSUE TITLE
DSpellCheck interferes with copying

### ISSUE THREAD

**Issue by coffent** [Predelnik/DSpellCheck#47]
When I highlight a line in Notepad++ v. 6.5.2 such as 

xxx the quick brown fox

then right-click it in preparation for copying, and DSpellCheck thinks the first word is misspelled, the highlighting is removed from all but that first word and when one clicks copy, only the first word is copied. If any other word is misspelled, e.g.

The xxx brown fox

the whole line is copied as expected.  I don't know whether the problem lies with NPP or DSpellCheck, but it can be quite frustrating.

**Comment by Predelnik** [comment]
I believe this was fixed since it wasn't reported by other users so closing, feel free to reopen if issues is still present.
