### ISSUE TITLE
'etc.' marked as misspelling, but suggestion is 'etc.'

### ISSUE THREAD

**Issue by plattrap** [Predelnik/DSpellCheck#48]
Seems to  be some interaction with the delimiters.

**Comment by rjbcollege** [comment]
Hi, 
I've also been experiencing this problem.
I think you've seen the issue from from the text here I'm not quite certain so, just to be clear, the symptoms I've had are these:-
etc. in text gets highlighted as a spelling error but the full stop is not included within the misspelling.
Listing the available corrections for this includes etc. with the full stop at the end.
Selecting that produces etc.. (with 2 full stops) with etc itself still being highlighted as a misspelling.
Repeating this process of course adds more full stops without other changes.
Many thanks.

**Comment by Predelnik** [comment]
I fixed this in 1.4.0 which is now available through plugin manager (better late than never).
Now etc. is spelled correctly only with dot if speller/dictionary supports it.
