### ISSUE TITLE
Incorrect threads shutdown leading to crash

### ISSUE THREAD

**Issue by ovk** [Predelnik/DSpellCheck#51]
In current implementation ThreadMain and ThreadNetwork threads may be still alive when FreeLibrary is called from Notepad++ plugin manager (when Notepad++ is closed). If this happens, notepad++ will be crashed because of access violation.

To make sure that threads are dead before DLL_PROCESS_DETACH received you need to use WaitForMultipleObjects on threads handles probably in NPPN_SHUTDOWN. And don't use this weird SendEvent (EID_THREADKILLED) and  ExitThread (0) in the end of each thread. Thus you will be guaranteed that both threads are dead after NPPN_SHUTDOWN and library can be safely freed.

**Comment by Predelnik** [comment]
Ok this bug seems to be fixed technically speaking, however there are still some problems left which I need to solve, mostly #53

**Comment by ariccio** [comment]
> 1.You can't do anything thread-related in DllMain. DllMain is completely single-threaded so when it's called with DLL_PROCESS_DETACH all your threads must be already dead.

BTW, application verifier has an option "DangerousAPIs" specifically for this sort of thing.

**Comment by ariccio** [comment]
Raymond Chen [has more](http://blogs.msdn.com/b/oldnewthing/archive/2014/08/21/10551659.aspx)
