### ISSUE TITLE
AppCrash with huge file

### ISSUE THREAD

**Issue by kreien** [Predelnik/DSpellCheck#57]
I am working with Windows 7 (32 bit), Notepad++ 6.6.9 (DSpellCheck 1.2.12). I have in Notepad++ a very huge file with 290.000 lines. Unfortunaletly with that file there is an application Crash (it is in German but understandable isn't it?):

Problemereignisname:    APPCRASH
  Anwendungsname:   notepad++.exe
  Anwendungsversion:    6.6.9.0
  Anwendungszeitstempel:    540cd326
  Fehlermodulname:  DSpellCheck.dll
  Fehlermodulversion:   1.2.12.0
  Fehlermodulzeitstempel:   52c4419f
  Ausnahmecode: 40000015
  Ausnahmeoffset:   00069654
  Betriebsystemversion: 6.1.7601.2.1.0.256.48
  Gebietsschema-ID: 1031
  Zusatzinformation 1:  3ff2
  Zusatzinformation 2:  3ff2e2a740c1273311bea630b5a08bb5
  Zusatzinformation 3:  ae20
  Zusatzinformation 4:  ae209d44a52db48c1d397f92bfc3ac90

With switched off DSpellCheck we have the same effect:
Problemsignatur:
  Problemereignisname:  APPCRASH
  Anwendungsname:   notepad++.exe
  Anwendungsversion:    6.6.9.0
  Anwendungszeitstempel:    540cd326
  Fehlermodulname:  DSpellCheck.dll
  Fehlermodulversion:   1.2.12.0
  Fehlermodulzeitstempel:   52c4419f
  Ausnahmecode: 40000015
  Ausnahmeoffset:   00069654
  Betriebsystemversion: 6.1.7601.2.1.0.256.48
  Gebietsschema-ID: 1031
  Zusatzinformation 1:  f688
  Zusatzinformation 2:  f68899164ab0bfeda6fe21292ccdb8f5
  Zusatzinformation 3:  7eae
  Zusatzinformation 4:  7eae2369e72a550bfbb7a4ea773b6e1a

Any ideas?

Best Regards
Michael

**Comment by Predelnik** [comment]
Since I believe even originally bug was not DSpellCheck related I'm closing this for now. Technically since DSpellCheck checks only visible line it should not be that dependant on whole file size, Notepad++ however may have some limitations in that field.
