### ISSUE TITLE
Please add support for hindi numerals and punctuation

### ISSUE THREAD

**Issue by Shreeshrii** [Predelnik/DSpellCheck#58]
Hi, Dspellcheck works well for hindi/sanskrit in devanagari script, but it marks all numbers and punctuation as incorrect. Please add support for the same.

**Comment by Predelnik** [comment]
To my shame this issue is still present in current versions of DSpellCheck. I made a fix so "Ignore words containing Numbers" would work for Hindi numbers and maybe for some other kinds of unicode numbers. It will be released with version 1.4.3.

**Comment by Predelnik** [comment]
Forget to close this somehow. Version with this fix is available through plugin manager.
