### ISSUE TITLE
Can not make permanent additions to Dictionary.

### ISSUE THREAD

**Issue by HereticWilson** [Predelnik/DSpellCheck#59]
Hi. I'm not sure if this is a problem with DSpellCheck or with np++. But, when I right click on a word that Dspellcheck doesn't recognize and tell it to add that word to the Dictionary, then close and reopen np++, that same exact word is once again underlined as if misspelled. I'm using the latest version of np++ if that matters.

**Comment by Ben-Voris** [comment]
This function works correctly for me. My user dictionary is %APPDATA%\Notepad++\plugins\config\Hunspell\en_US.usr

**Comment by Predelnik** [comment]
At least one of such problems was resolved in version 1.3.1. Sorry for a late fix.

**Comment by Predelnik** [comment]
Since this problem was probably fix and is quite old I'm closing this for now, freel free to reopen.
