### ISSUE TITLE
"Enrollment" improperly marked misspelled

### ISSUE THREAD

**Issue by juventus18** [Predelnik/DSpellCheck#60]
the word "enrollment" is marked as misspelled, but it is the correct spelling. The program will suggest "enrolment" as the fix, however this is incorrect.

**Comment by Predelnik** [comment]
This is the problem with dictionary and is actully difference between British and American English. There are separate dictionaries for both.

Problems with the dictionaries are either way off-topic:
https://github.com/Predelnik/DSpellCheck/wiki/Bug-Reporting#bugs-related-to-dictionaries
