### ISSUE TITLE
Romanian spellcheck dictionary is very old

### ISSUE THREAD

**Issue by cristianadam** [Predelnik/DSpellCheck#61]
Hi there,

I've seen that DSpellCheck is using OpenOffice dictionaries. Unfortunately OpenOffice has an old Romanian dictionary.

http://rospell.wordpress.com/download/ has up to date Romanian dictionaries.

The above dictionaries are used for Firefox and LibreOffice.

Here are some numbers:

|  | ro_RO.dic Open Office | ro_RO.dic LibreOffice (rospell) |
| --- | --- | --- |
| size | 331 KB | 2.09 MB |
| words | 33.275 | 181.357 |
| utf-8 | no | yes |
| using correct romanian (șț) | no | yes |

Any chance of fixing this?

I've manually copied the dictionary files (ro_RO.aff, ro_RO.dic)  to `%appdata%\notepad++\plugins\config\hunspell`. Works perfectly.

It would be great if it would work out of the box.

**Comment by einst3** [comment]
open office is no longer maintained.

**Comment by chcg** [comment]
Seems https://github.com/LibreOffice/dictionaries/tree/libreoffice-5.4.4.1 has the same stucture as the OO ftp repos, but there seems to be no ftp server containing that extraced, just as package, e.g.
http://ftp.tu-chemnitz.de/pub/tdf/libreoffice/src/5.4.4/libreoffice-dictionaries-5.4.4.1.tar.xz

**Comment by Predelnik** [comment]
Well taking dictionaries from github is possible option. It probably would also be nice to display their readme since it contains license info but they seem to be a bit unstructured in that regard.

**Comment by chcg** [comment]
@Predelnik  But that would require a http connection and as far as I see currently the code just supports ftp, so something like curl might be needed. I also tried to download libreoffice-dictionaries-5.4.4.1.tar.xz, extract it and add some local path to the download dictionary dialog, but that doesn't work "yet".

**Comment by Predelnik** [comment]
Well there's always WinInet. Some part is already done through it. As for local paths I don't know if it's required, seems like if person download all dictionaries he should just choose the ones he want using filesytem.

**Comment by chcg** [comment]
You are right, if someone already downloaded and extracted the stuff, it should be no problem to do the final copy step also manually, like described in How to install manually dictionaries #62.

One offtopic thing: ftp://gd.tuwien.ac.at/office/openoffice/contrib/dictionaries/ seems to be not accessible and also ftp://gd.tuwien.ac.at/

**Comment by Predelnik** [comment]
Yeah I noticed that but didn't bother to remove for a while, probably should do it at some point.

**Comment by Predelnik** [comment]
Since downloading dictionaries from GitHub was implemented this issue should be mostly resolved.
