### ISSUE TITLE
Settings overwritten after Notepad++ start

### ISSUE THREAD

**Issue by janschreiber** [Predelnik/DSpellCheck#64]
With version 1.2.14.0 of DSpellCheck, all my settings are overwritten with default values after a fresh start of Notepad++.

**Comment by Predelnik** [comment]
Just checked it. Seems fine to me. Do you have any additional details or maybe steps to reproduce?

**Comment by janschreiber** [comment]
The above error description was misleading, sorry.
The problem seems to be that the delimiters aren't read from DSpellCheck.ini when I start Notepad++.
When I add the „ character (opening German quotation mark) to the delimiters, everything works fine for the session, but when I restart Notepad++, a string like „test is marked as an error again, and the „ char does not show up as delimiter in the DSpellCheck settings.

**Comment by Predelnik** [comment]
Yeah that's weird and certainly isn't happening in 1.2.12. Need to fix is asap, thx for reporting!

**Comment by Predelnik** [comment]
Ok I fixed it and reuploaded the version since it wasn't picked up by auto update yet. Funny that this bug was introduced because I fixed suspicious code found by turning higher level of warnings.
