### ISSUE TITLE
Windows 8+ native spell checker

### ISSUE THREAD

**Issue by tbs** [Predelnik/DSpellCheck#65]
Recently Hexchat irc client has implemented support to Windows 8+ native spell checker, it works very well. No need to download extra files, all dics are already built in on system.

Here you can see the code changes:

https://github.com/hexchat/hexchat/commit/96026b82c784bbba010d0a9550301cefd6c73af7

And here are the test build which already has the feature:

http://dl.hexchat.net/hexchat/testing/

Would be awesome if you can implement the same thing to DSpellCheck.

Thanks.

**Comment by Predelnik** [comment]
Oh so that's the thing that annoys me in Skype :) But sure suggestion is valid and doesn't look very hard to implement.

**Comment by Predelnik** [comment]
Native spell-checker was supported as the third available speller in version 1.4.0 which is now available through plugin manager. Even though a lot of internal infrastracture was changed to make it at least not unusably slow, it still works noticeably slow compared to native Hunspell and Aspell. But some performance improvements may still come later.

As a positive thing about it - dictionaries quality seems to be very good and indeed do not require any downloading usually.
