### ISSUE TITLE
About new version (12.14.1) of DSpellCheck

### ISSUE THREAD

**Issue by DmFedorov** [Predelnik/DSpellCheck#67]
I tried a new version of Np ++ 5.7.9.
This version is  very crude and hangs regardless of your plugin. This version uses a patch to resolve the issue with the constant files-saving  during the session.
As a result, during the start of Np ++ it loads CPU so, that it even cannot draw the dialogue of its settings.
In addition an unexpected way the font (that was not changed since the first day of release) now is changed.
You need wait for the normal version of Np ++.

**Comment by Predelnik** [comment]
Have you created issue about that in N++ repo? Probably issues of DSpellCheck are not so connected with that anyway.

**Comment by Predelnik** [comment]
Since I don't think that this issue was related to DSpellCheck to begin with, I'm closing this.
