### ISSUE TITLE
'Due to the stability issue, DSpellCheck.dll will be moved to the directory "disabled"'

### ISSUE THREAD

**Issue by JVimes** [Predelnik/DSpellCheck#70]
Upon upgrading to Notepad++ v6.8.1, I get:
![2015-08-20_20h45_16](https://cloud.githubusercontent.com/assets/6148201/9400257/aa7a071a-477c-11e5-868c-0fb4183082b0.png)

Haven't gotten this with previous updates.

**Comment by Predelnik** [comment]
Sadly that "issue" is with Notepad++ installer, not much I can do about it.
see https://github.com/notepad-plus-plus/notepad-plus-plus/issues/427

**Comment by JVimes** [comment]
Thanks, just making sure it was reported somewhere. ☺
