### ISSUE TITLE
Comment/String checking for CoffeeScript

### ISSUE THREAD

**Issue by dail8859** [Predelnik/DSpellCheck#71]
CoffeeScript was added back in v6.5 and DSpellCheck is missing support for its comments/strings styles. It also looks like SciLexer.h will have to be updated since it doesn't have those styles, see the current [SciLexer.h](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/include/SciLexer.h#L1666) in the N++ repo.

![img](https://cloud.githubusercontent.com/assets/3694843/11399825/bf013538-9357-11e5-8dd8-e888d2348678.png)

**Comment by Predelnik** [comment]
SciLexer was updated and all new languages from it were more or less supported in 1.4.0. There are still may be some issues because I'm not familar with a lot of those languages but they can be resolved on case by case basis.
