### ISSUE TITLE
"Installation of DSpellCheck failed."

### ISSUE THREAD

**Issue by coffent** [Predelnik/DSpellCheck#72]
I had DSpellCheck installed and working well, but I believe in a recent NPP update it said there were compatibility issues with DSC and it would be disabled (as I recall!).  (I have the latest v.6.8.6 of NPP.)  Plugin Manager does NOT list DSC as a currently installed plugin, but when I try to use it to install DSC I get the rather unhelpful message "Installation of DSpellCheck failed."  Any ideas why?

**Comment by Predelnik** [comment]
Hello it seems to be installing fine for me from plugin manager, maybe it
has something to do with access rights. However it seems that Notepad++
currently will move DSpellCheck.dll to disabled plugins after each update
which is quite unfortunate.

Best regards, Sergey Semushin

**Comment by Troop666** [comment]
Any news?

**Comment by Troop666** [comment]
Workaround.
1) close npp
2) del c:\Program Files (x86)\Notepad++\plugins\disabled\DSpellCheck.dll
3) download https://github.com/Predelnik/DSpellCheck/releases/download/1.2.14.2/DSpellCheck.zip
4) unpack to c:\Program Files (x86)\Notepad++\plugins\
5) start npp

**Comment by chcg** [comment]
Since https://notepad-plus-plus.org/download/v7.5.2.html DSpell 1.3.2 is part of the n++ package again and this issue should not appear any longer. See also https://notepad-plus-plus.org/download/v7.5.3.html which fixes an issue with the installer version of N++ and the correct installation of the  DSpellCheck plugin.

**Comment by Predelnik** [comment]
This shouldn't be a problem anymore as @chcg mentioned, so I'm closing this for now but feel free to reopen the issue if you still have problems.
