### ISSUE TITLE
Delimiters list has character encoding issues and gets corrupted

### ISSUE THREAD

**Issue by Dwedit** [Predelnik/DSpellCheck#79]
Sometimes, when I add Unicode characters to the delimiters list and run Notepad++ again at a later date, I see the delimiters list now has substituted characters in there, some delimiters have turned into ?.  I even saw a plain lowercase 'c' in there, which greatly disrupted spell checking.

**Comment by Predelnik** [comment]
Quite late answer, but it will be fixed in 1.3.3. See #108

**Comment by Predelnik** [comment]
The issue is closed since version 1.3.3 is avilable through plugin manager.
