### ISSUE TITLE
DSpellCheck 1.2.14.2 doesnt work with latest Notepad++

### ISSUE THREAD

**Issue by un1versal** [Predelnik/DSpellCheck#81]
I sometimes use Windows 7 sp1 64-bit with Notepad++ 6.9.2 64-bit and have moved the DSpellCheck 1.2.14.2 dll from the disabled folder and can use a very limited DSpellCheck functions.

The main issue is adding new words to the dictionary, these changes are 100% lost, 100% of the time, since these are re-occurring words often used, this is really a put off.

For months now, theres no fully working spellchecker may as well not exist anyway.

The only alternative spellchecker is utterly useless as it is incomplete and requires further programs/libraries to be installed... The point is DSpellCheck is broken and requires TLC.

Ill happily provide more information just no idea what or how to tbh it windows after all, just let me know what you need and how to get that information and Ill post it ASAP.

Thanks.

**Comment by einst3** [comment]
computer config: w7x64 latest sp, npp7.3.0, npp appdata installed plugins.
unified dictionary was not saving my added items to UserDic.dic. i downloaded dictionaries and changed to unified dictionary. does not save changes.
i did get the en_US.usr to start saving though. steps to take... install plugin, download dictionaries from settings, set default language to en_US and it now saves my settings in the en_US.usr.

**Comment by alexolog** [comment]
Windows 10, latest NP++, misspelled words are not underlined.

**Comment by Predelnik** [comment]
If the issue has the same nature as @einst3 comment it was fixed in version in 1.3.1, see #87. If not I can diagnose it further if you still interested, sorry for late answer.

**Comment by Predelnik** [comment]
Since it's most likely was fixed in 1.3.1 I'm closing for  this now, feel free to reopen if you're still having problem.
