### ISSUE TITLE
Launch error: DSpellCheck v1.2.14.2 (2016.04.23) with notepad++ 7.1 x64 on Windows 10 x64

### ISSUE THREAD

**Issue by Galixte** [Predelnik/DSpellCheck#84]
Hi @Predelnik & @edwpang ,

If i put the last version of DSpellCheck availables here: https://github.com/Predelnik/DSpellCheck/issues/53#issuecomment-213636401.

in plugins folder like this: C:\Program Files\Notepad++\plugins\DSpellCheck.dll,

and when i launch notepad++ 7.1 x64, i have this error message:

```
Cannot load 32-bit plugin.

DSpellCheck.dll is not compatible with the current version of Notepad++.

Do you want to remove the plugin from the plugins directory to prevent this message from the next launch? 
```

**Comment by Predelnik** [comment]
Sadly I haven't tried to compile 64-bit version yet. I may look into it soon.

**Comment by Galixte** [comment]
Thanks !-)

**Comment by Predelnik** [comment]
So I've made a little preview version, just by quickly fixing all build warnings. Seems to work me. You may try it out for now.
https://github.com/Predelnik/DSpellCheck/releases/download/1.2.14.2/DSpellCheck-x64.zip

**Comment by Galixte** [comment]
Hi,

thanks a lot ! It works for me too. ;)
