### ISSUE TITLE
additional x64 changes needed

### ISSUE THREAD

**Issue by xomx** [Predelnik/DSpellCheck#86]
- all BOOL CALLBACK DlgProc(UINT, WPARAM, LPARAM) funcs have to be changed to INT_PTR CALLBACK DlgProc(UINT, WPARAM, LPARAM)

- there is a lot of places, where casting or changing a param type is needed e.g.:

  -> ptr arithmetic like:  long offset = charptr1 - charptr2;    have to be changed into:  size_t offset = charptr1 - charptr2;    (or not so good casting to long: long offset = (long)(charptr1 - charptr2))

  -> WM funcs returning type (LRESULT) have to be changed accordingly, e.g.:  int lengthDoc = (int)(SendMsgToActiveEditor (&ok, GetCurrentScintilla (), SCI_GETLENGTH) + 1);

  -> size_t is platform dependent, so additional casting to int, long, etc. when necessary, e.g. int size = (int)_tcslen(SysDicDir)...

After all these changes it works ok, tested under npp 7.2.2 x64.

**Comment by Predelnik** [comment]
Isn't it all done already?
https://github.com/Predelnik/DSpellCheck/commit/efcac30a598bc0af0f83bcba520dfc2df948c8f5

**Comment by xomx** [comment]
I just downloaded the zipped project from github, generated an appropriate sln with cmake and tried to build x64 under MSVS2013 - and there were all these build blocking problems I described. Now I see in your commit that all of these have been fixed already, strange.

**Comment by Predelnik** [comment]
Looks like it's because I've applied fixes to 'stable' branch only and haven't merged it to master yet. I guess I need to sort this out, sorry for inconvenience.

**Comment by chcg** [comment]
@Predelnik Probably could be closed now with the release of version v1.3.0.
