### ISSUE TITLE
unified dictionary UserDict.dic not saving added words

### ISSUE THREAD

**Issue by einst3** [Predelnik/DSpellCheck#87]
computer config: w7x64 latest sp, npp7.3.0-7.4.1-x86, dspellcheck 1.2.14.2.
note: npp appdata installed plugins

unified dictionary is not saving my added words to UserDic.dic. i downloaded dictionaries and changed to unified dictionary. does not save changes. dspellcheck.ini...
[SpellCheck]
Hunspell_Multiple_Languages=en_GB|en_US|fr_FR|de_DE|el_GR|la|es_NEW
Hunspell_Language=&lt;MULTIPLE&gt;
Suggestions_Number=9
United_User_Dictionary(Hunspell)=1

note: npp appdata installed plugins
i did get the en_US.usr to save though. steps to take... install plugin, download dictionaries from settings, set default language to en_US and it now saves my settings in the en_US.usr. dspellcheck.ini...
[SpellCheck]
Hunspell_Multiple_Languages=en_GB|en_US|fr_FR|la|es_NEW
Hunspell_Language=en_US
Suggestions_Number=9

**Comment by einst3** [comment]
any thoughts on this, anyone?

**Comment by Predelnik** [comment]
Will be fixed in 1.3.1.
