### ISSUE TITLE
Does recog. strings with 'single quotes' 

### ISSUE THREAD

**Issue by Djamana** [Predelnik/DSpellCheck#88]
In Npp I've some python file and set DSpellCheck to english
... and added these three lines

![screenshot_20170214_144223](https://cloud.githubusercontent.com/assets/7028778/22931144/d7649f4e-f2c3-11e6-8afa-191766c24169.png)

The first two get the this red underline (showing that this word is misspelled)

but for the last with 'single quotes' this red underline is missing.
-> DSpellCheck somehow doesn't consider this as string

But would be nice it it does.  :^)

**Comment by Predelnik** [comment]
Should work fine starting 1.4.0 version which is now available on plugin manager.
