### ISSUE TITLE
Broken link at Plugin_Central

### ISSUE THREAD

**Issue by zekrom-vale** [Predelnik/DSpellCheck#90]
[Drop Box](https://dl.dropboxusercontent.com/s/1iktb3a9i1d6afd/DSpellCheck.dll) at [Plugin_Central](http://docs.notepad-plus-plus.org/index.php/Plugin_Central) gives a 403 error.

>![image](https://user-images.githubusercontent.com/27376918/27516853-4e9bc644-5987-11e7-8a2d-c78ccce566b7.png)
>It seems you don't belong here! You should probably sign in. Check out our Help Center and forums for help, or head back to home.

**Comment by Predelnik** [comment]
Hmm that's true but I can't understand to how to register for editing that wiki now, it seems like in the past login base was different. Do you have any idea per chance?

If not I will ask in N++ forum.

**Comment by Predelnik** [comment]
I asked about it here:
https://notepad-plus-plus.org/community/topic/14616/access-to-plugin-central
(Posting to keep track about the topic)

**Comment by Predelnik** [comment]
Seems like this site is no longer accessible now even, I will close the issue if it stays that way.

**Comment by Predelnik** [comment]
It continues to be inaccessible, closing the issue now.
