### ISSUE TITLE
Can't build DspellCheck

### ISSUE THREAD

**Issue by SinghRajenM** [Predelnik/DSpellCheck#96]
Can't build DSpellCheck (neither master nor ver_13 branch).

As per build process define at [wiki](https://github.com/Predelnik/DSpellCheck/wiki/Manual#-4-building-dspellcheck), it can be built using VS 2005 also.
But it can't be built even using VS2015 also as it uses C++17 features. Is there any specific need to use it?

![image](https://user-images.githubusercontent.com/14791461/30883792-fc7ca4b2-a32a-11e7-8206-dd30464a1b18.png)

**Comment by Predelnik** [comment]
Sorry now only vs2017 is supported. I will update wiki.

**Comment by SinghRajenM** [comment]
Okay, no problem. Going forward I will use VS 2017.
